### ISSUE TITLE
Maple Finance Schema: 1.3.0 Subgraph: 1.1.0 Methodology: 1.0.0 `totaldepositbalanceUSD` incorrect

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1001]
`totaldepositbalanceUSD` should match `totalvaluelockedUSD`, reporting below that, could be reporting `totalborrowedbalanceUSD`

![Screen Shot 2022-09-14 at 3 36 23 PM](https://user-images.githubusercontent.com/47088402/190246526-f8dbed02-0f49-4a57-8318-6927fb4403bb.png)
![Screen Shot 2022-09-14 at 3 36 51 PM](https://user-images.githubusercontent.com/47088402/190246571-b47e1c49-ff7c-4cc1-a95a-6bdec049bab0.png)

**Comment by this-username-is-taken** [comment]
@tnkrxyz would you take on this?

**Comment by tnkrxyz** [comment]
> @tnkrxyz would you take on this?

of course

**Comment by tnkrxyz** [comment]
Looking at the implementation, the difference is due to the methodology (documented in [README.md](https://github.com/messari/subgraphs/tree/master/subgraphs/maple-finance#total-value-locked-tvl-usd)) in defining `totaldepositbalanceUSD` and  `totalvaluelockedUSD`:

`totalvaluelockedUSD = Cumulative Deposit USD - Cumulative Withdraw USD - Cumulative Pool Losses USD` and 
`totaldepositbalanceUSD = Total Deposit Balance USD + Total Stake Balance USD + Total Unclaimed Supplier Interest USD`

The implementation takes into account staking; not sure whether this should be included (I haven't included in the few lending protocols I implemented). It seems to me `Total Unclaimed Supplier Interest USD` should not be included.

Anyone can clarify whether they are intended?

**Comment by this-username-is-taken** [comment]
@ishraq8

**Comment by ishraq8** [comment]
@tnkrxyz Yes you are correct. Maple, like all other lending protocols should not include staking as part of their TVL. This inconsistency will cause problem when making dataapps. I've put in a pull request to correct this issue in the readme. Will also need to be corrected at code level. 
 
https://github.com/messari/subgraphs/pull/1086

**Comment by tnkrxyz** [comment]
@ishraq8 , are you going to make the change to the code? If not, I can do it.

**Comment by ishraq8** [comment]
@tnkrxyz Please go ahead and change the code, thank you! Dylan is giving me a crash course on subgraph coding later this week so not super comfortable making changes til then :).

**Comment by tnkrxyz** [comment]
OK, done.

**Comment by ishraq8** [comment]
thanks @tnkrxyz, appreciate your help!
