### ISSUE TITLE
Vesta Finance Arbitrum QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1044]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/corerouter/vesta-finance&tab=protocol
| Schema Version  |  1.3.0  | 
| Subgraph Version |  1.0.1  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1sOxW5_8NPQKHJKbw0OJQBKQuWA3BR20V/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Revenue

- We did computations for the supply side revenue, protocol side revenue, and daily total revenue using data from Dune and the results show a large discrepancy ranging from 21% to 177% with subgraph data. This may be due to the reason liquidation events and its subsequent USD values are not captured correctly 
- The queries are: 
   - https://dune.com/queries/1290422
   - https://dune.com/queries/1286749
- Refer to the sheet 'Protocol' under the respective items for details.

|Subgraph Daily Supply Side Revenue |Dune Analytics| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|156.95 | 110 |46|42.68%|

|Subgraph Daily Protocol Side Revenue |Dune Analytics| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
|1,149| 946.90 | 202|21.34%

|Subgraph Total Daily Revenue |Dune Analytics| Absolute Difference |% Difference |
| :---- | :--- | :---  | :---  |
| 1306 | 1056 | 246 |23.57%

### Max LTV of gOHM pool
This should be 66.7% instead of 90.1%.

**Comment by corerouter** [comment]
Thank you very much for your test. Please find my feedback and questions on these issues raised.
1. For Daily Supply Side Revenue, would you please let me know how the dollar value of 110 was computed? 
The Dune dashboard only provide asset number and debtUSD and doesn't have any asset price info from https://dune.com/queries/1290422. It is important for me to find the root cause for the dollar value difference as I find the asset value is right.
2. For Daily Protocol Side Revenue and Total Daily Revenue, I fixed a constant in the subgraph and now the data is more in line with Dune dashboard at https://dune.com/queries/1286749. I also noticed in Dune the redemptions revenue for GMX and gOHM is not included as there are not price info for them as shown below, so it is also a reason for data difference in some day.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/28422812/192523603-b21140fb-48b2-4310-989a-7c19e2631fb8.png">
3. The maxLTV data error for some markets such as gOHM have been fixed.

**Comment by ishraq8** [comment]
@corerouter 
1) I double checked the revenue using: https://dune.com/queries/1286749. The dates available on the the dune dashboard match the subgraph. There are revenue dates on the dune that is not on the subgraph. is that because there is no block data?
2) Would it be possible to get GMX and gOHM oracle price? @dmelotik do you know if this is possible?
3) Max LTV looks fixed.

**Comment by dmelotik** [comment]
> Would it be possible to get GMX and gOHM oracle price? @dmelotik do you know if this is possible?

Like on the subgraph? I think @corerouter is saying the dune dashboard doesn't have the gOHM and GMX price

**Comment by ishraq8** [comment]
Ah ok my bad

**Comment by corerouter** [comment]
@ishraq8 Thank you very much for your kind response.
1. For the revenue data, I compared the subgraph with Dune and didn't find any revenue dates missing on the subgraph. As shown below, the latest 150 entries for protocol revenue on subgraph dates back to May 2 while Dune dates back to May 1 as the subgraph show the real time date on Sep 28 while Dune didn't. So I don't think there is any missing days for the revenue data in the subgraph so far.
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/28422812/192772790-33641394-7e25-4942-af21-4056d728a8d2.png">
2. For the GMX and gOHM prices, the subgraph gets them from Vesta internal oracle. I think Dune dashboard try to get them from Dune internal prices database but find there are not prices for the two tokens so far.

Thanks!

**Comment by this-username-is-taken** [comment]
@ishraq8 what's the status on this?

**Comment by ishraq8** [comment]
My mistake this subgraph is done and ready for prod. 
Thank you @dmelotik @corerouter 
Version QAed was: https://thegraph.com/hosted-service/subgraph/corerouter/vesta-finance

**Comment by dmelotik** [comment]
One last change needs to be made then deploying to prod!
