### ISSUE TITLE
Build Aura Subgraph

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1067]
@dhruv-chauhan

**Comment by SerenityFund** [comment]
| Item | Info |
| :---- | :--- |
| Date Reviewed  | 06-Oct-22 |
| Schema Version  | 1.3.0 |
| Subgraph Version  | 1.1.0 |
| Methodology Version  | 1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1yW6KrnHKx2pYY7-F4cTRbZ4WifEvsnUh/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

## Metric to Review

### Rewards
The rewards are generally less than that stated in the official website. It seems that a 25% is applied to the official rewards ratio.

| Pool | Subgraph | Official Website |
| :---- | :--- |  :--- |
| wesETH-ETH | 0.85% | 3.43% | 
| bb-a-usd | 0.46% | 1.85% | 

### Revenue
We note that the revenue stream patterns of the pools are different. Some are continuous and some are intermittent. Please refer to the "Top 5 Revenue" sheet for more info.

### Pool Overview TVL
Sum of all pool TVL is in line with the subgraph. Out of 49 pairs included in the subgraph, 12 pairs are inactive pools bringing a total of 37 pools which matches the websites data. In addition there is no staBAL3 pool although the TVL matches DAI USDC USDT pool from the website. Meanwhile 50Silo-50WETH and MAI-USDC-SP have pool TVL  discrepancies. 

| 50Silo-50WETH| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 362,955.32| 286,590 | 76,365.32| 26.65%|

| MAI-USDC-SP| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 152,910.41| 903,230 | -750,319.59| -83.07%|

- Refer to the sheet "Pool_Overview" for details

**Comment by dhruv-chauhan** [comment]
### Rewards
Pool | Subgraph | Official Website
-- | -- | --
wesETH-ETH | 3.37% | 3.24%
bb-a-usd | 1.94% | 1.92%

### Revenue
Event `RewardAdded` is emitted when new BAL rewards are allocated to a pool. BAL rewards are queued and the distribution only begins once the new rewards are sufficiently large, or a duration (7 days) has passed. Hence, stream patters of pools might look intermittent and with harvesting every 7 days.

### Pool TVL
staBAL3 pool is same as the DAI USDC USDT pool from website. The [Balancer Pool Token](https://etherscan.io/address/0x06df3b2bbb68adc8b0e302443692037ed9f91b42) (= inputToken for aura vault) for DAI USDC USDT pool uses name `Balancer USD Stable Pool` and symbol `staBAL3`.
 
Pool | Subgraph TVL | Official Website TVL
-- | -- | -- 
50Silo-50WETH | 293k | 293k
MAI-USDC-SP | 1.30m | 1.29m

@SerenityFund

**Comment by bye43** [comment]
@dhruv-chauhan The problems above look solved! I just had a few questions about some things below, but otherwise everything else looks good. 

### Issues 
Pool | Metric | Issue
-- | -- | --
Balancer 50 WBTC 50 WETH (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-7) | Rewards | AURA APR is 1.07% on the subgraph and 0.66% on Aura UI. I am guessing that this is because rewards are harvested over 2 - 3 days and subgraph calculation is accounting for just the accumulation of those rewards today, but just want to double check.
50INV-50DOLA(0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-37) | TVL | Subgraph TVL is $853,780.02 and Aura UI is $410,240. This looks like a pricing issue with the LP since it seems like the subgraph is recording the correct amount of LP tokens staked. We are recording the price as ~8 (https://api.thegraph.com/subgraphs/name/dhruv-chauhan/aura-finance-mainnet/graphql?query=%7B%0A++vault+%28id%3A+%220x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-37%22%29+%7B%0A++++inputToken+%7B%0A++++++name%0A++++++lastPriceUSD%0A++++%7D%0A++%7D%0A%7D) and Aura UI is recording $4.01.
20WBTC-80BADGER (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-11) | All Metrics | I cannot find this pool anymore on the Aura UI. I think potentially this pool was deprecated and moved to index 33. When I look at the gauge for this contract and query the Aura staker address (0xaF52695E1bB01A16D33D7194C28C42b10e0Dbec2) it does not look like there is a balance (https://etherscan.io/address/0x3F29e69955E5202759208DD0C5E0BA55ff934814#readContract).

**Comment by dhruv-chauhan** [comment]
1. Balancer auraBAL Stable Pool (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-19)

Since we don't get prices of input tokens from price-lib, we calculate them using token weights, balances and price of any known token. The math checks out.

<details>
  <summary>the method:</summary>
  
    1. iterate over input tokens
        - recursively check if the input token is a Balancer pool token itself, go to 1
        - get price from price-lib, save it's index
    2. if price for any one token is known, we can calculate the prices of other unknowns using token weights, balances and price of known token
</details>

<details>
  <summary>the math:</summary>

    B-auraBAL-STABLE
    input tokens: B-80BAL-20WETH and auraBAL

    1. B-80BAL-20WETH
        input tokens: BAL and WETH
        
        1.1. BAL
            balance = 23506679,619517607117471489
            price = 4.83

            value = 113537259   [balance*price]
        1.2. WETH
            balance = 22360,290283950712088528
            price = 1286

            value = 28754960    [balance*price]

        supply = 11469599,795000886785889325
        balance = 427075,336665277971472029

        => tvl = 142292219      [summation of vaules]
        => price = 12.4         [tvl/supply]
        => value = 5295730      [balance*price]


    2. auraBAL
        scales = 1:1
        balance = 594123,262952934467815933

        => weights = 50:50      [weight=(scale/summation of scales)*100]
        => value = 5295730      [valueB=valueA*(weightB/weightA)]
        => price = 8.91         [value/balance]


    supply = 995326,844329251703069445

    => tvl = 10591460           [summation of vaules]
    => price = 10.64            [tvl/supply]
</details>

2. Balancer 50 WBTC 50 WETH (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-7)

looks fine to me, please recheck
![Screenshot from 2022-10-13 17-18-57](https://user-images.githubusercontent.com/32761670/195608111-19fca546-ed85-4e0e-861e-4868cd311e59.png)

3. 50INV-50DOLA (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-37)

looks fine to me, please recheck
![Screenshot from 2022-10-13 17-20-20](https://user-images.githubusercontent.com/32761670/195608415-6d076873-3300-43e8-9954-2a310efef5d5.png)

4. 20WBTC-80BADGER (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-11)

This is an inactive pool. Inactive pools are not visible on Aura UI by default, but you can check the pool page [here](https://app.aura.finance/#/pool/11). 
To indicate the pool status, we have added a field `_active` in `vault` entity, [query](https://api.thegraph.com/subgraphs/name/dhruv-chauhan/aura-finance-mainnet/graphql?query=%7B%0A++vault+%28id%3A+%220x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-11%22%29+%7B%0A++++name%0A++++_active%0A++%7D%0A%7D).

Checked calculated TVL for this pool, looks fine to me:
- 20WBTC-80BADGER deposit [balance](https://etherscan.io/token/0x1ba9e3ec7dff02b6cfa4bbfe2180b9a3011efd39?a=0xcea3aa5b2a50e39c7c7755ebff1e9e1e1516d3f5)
- 20WBTC-80BADGER [price](https://api.thegraph.com/subgraphs/name/dhruv-chauhan/aura-finance-mainnet/graphql?query=%7B%0A++tokens%28where%3A+%7Bsymbol%3A%2220WBTC-80BADGER%22%7D%29%7B%0A++++symbol%0A++++lastPriceUSD%0A++%7D%0A%7D)

@bye43

**Comment by bye43** [comment]
@dhruv-chauhan Thanks for the explanations! I just re-checked on Aura and looks like most of the pricing things just updated to our values. And ya, that is my bad just re-queried 20WBTC-80BADGER (0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10-11) and everything looks good. @this-username-is-taken this is good to go and going to close the issue.
