### ISSUE TITLE
Create custom format rules

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1079]
In an effort to normalize and create efficient workflows across messari/subgraphs. We want to have consistent formatting. This makes it easier to read, refactor, and add new code.

This effort is similar to the work being done on #1022 and can be looped into a similar set of tools.

**Comment by dmelotik** [comment]
Tried implementing with no luck @bye43 . Thinking of canning this bc it is not worth any more effort

**Comment by jaimehgb** [comment]
You almost had it @dmelotik 🙈 

Since we have prettier already installed at the root of the project (it’s on package.json), installing those dependencies and making it a npm script did the trick. When doing `npm install` npm then runs the post install scripts, which in this case would install husky. You can avoid that with `run: npm ci --ignore-scripts`, as we have in other jobs.

For the files changed, since we are already using something to determine which subgraphs to build based on the files that got changed we can reuse that too.


Seems to be working for me here:
https://github.com/messari/subgraphs/pull/1648
Unless I’m missing some edge case. What issues did you find?
