### ISSUE TITLE
New lending schema (Positional / new relations in markets)

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1081]
As we have developed lending protocol subgraphs, we have learned numerous things that will help us refine our lending positional data.

Learnings:
- Not every pool borrows the same asset as is in the pool. Take abracadabra for example.
- We learned that positions can be passed around outside of protocol owned contracts. cTokens can be transfered to wallets that never touch a market. Is this a new position, do we increment deposits, new user? We need to answer these questions
- Aave v2 is tough and needs more research to understand how swaps within the protocol create new positions.
- Lots of notes have been made here #389 
- SimpleFi has already done some work on this, planning to connect with them to learn more and collaborate

**Comment by ishraq8** [comment]
Thanks for this, do you mind if i join the conversations with simplefi? i was going through the docs you shared.

https://github.com/SimpleFi-finance/subgraphs

**Comment by dmelotik** [comment]
Linking notion of proposed changes: https://www.notion.so/messari/Lending-Protocol-Schema-cbc6f46a75044bb5829e29d12f7004d2

**Comment by ishraq8** [comment]
Making note of issue https://github.com/messari/subgraphs/issues/966

https://twitter.com/omeragoldberg/status/1568118558982389760?s=46&t=YqJRaYypMHCTU9e4e92Qhg
https://chaoslabs.xyz/posts/chaos-labs-dives-deep-into-aave-v3-data-validity

For AAVE V3 positional data when withdrawing a supply position the contract burns the atokens withdrawn-the interest accumulated since last update. So for positional data someone can have no supply but still have atokens. 

Since our subgraph is tracking both deposit/withdraw and atokens seperately we can just make a note in the docs to address this potential descrepancy for aave v3.

**Comment by dmelotik** [comment]
This is done now
