### ISSUE TITLE
Arrakis Optimism QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1190]
| Item | Info |
| :---- | :--- | 
| Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=l0c4t0r/laboratory2&tab=protocol |
| Date Reviewed  | 09-Oct-22 |
| Schema Version  | 1.3.0 |
| Subgraph Version  | 1.1.0 |
| Methodology Version  | 1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1GQ5y8tE1G8OS_QHo0edirFzTUniT-LqC/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Revenue

- Data matches calculations for the daily supply side revenue, daily protocol side revenue, and daily total revenue. However, lifetime fees earned or the cumulative revenue from the subgraph does not match the official website. The discrepancy in fees earned come from WETH/ALIEN and WETH/SNX. Not to mention STG / USDC pool has fees tracked in Uniswap which does not match 0% lifetime APR and 0 fees in their website. 
- We also note that out of the 8 vaults, 4 of them do not have updated subgraphs.
- Refer to the sheet 'Daily Graph'
- Refer to the sheet 'Revenue'

| WETH/ALIEN| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 130,769.11| 33,629.34 | -97,139.77| 288.85%|

| WETH/SNX| Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 51,691.69| 26,669.44 | -25,022.25| 93.82%|

### Cumulative Unique Users
The daily and hourly cumulative unique user data do not match.

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@l0c4t0r QA for Arrakis OP is done. Not sure if you got notified, so just wanted to make sure. Thanks!

**Comment by l0c4t0r** [comment]
Must have missed this. Thanks, will review feedback

**Comment by bye43** [comment]
@l0c4t0r Do you mind sharing the new deployment link for this?

**Comment by l0c4t0r** [comment]
Sorry i overwrote it with something else. Let me redeploy.

**Comment by tnkrxyz** [comment]
> ## Metric to Review
> ### Revenue
> * Data matches calculations for the daily supply side revenue, daily protocol side revenue, and daily total revenue. However, lifetime fees earned or the cumulative revenue from the subgraph does not match the official website. The discrepancy in fees earned come from WETH/ALIEN and WETH/SNX. Not to mention STG / USDC pool has fees tracked in Uniswap which does not match 0% lifetime APR and 0 fees in their website.
> * We also note that out of the 8 vaults, 4 of them do not have updated subgraphs.

@SerenityFund  Can you pls clarify what you do mean "out of the 8 vaults, 4 of them do not have updated subgraphs". From my deploy of the optimism subgraph (https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/arrakis-finance-optimism&tab=poolOverview), it seems to be all synced? 

> 
> WETH/ALIEN	Official Website	Absolute Difference	% Difference
> 130,769.11	33,629.34	-97,139.77	288.85%
> WETH/SNX	Official Website	Absolute Difference	% Difference
> 51,691.69	26,669.44	-25,022.25	93.82%

It seems part of the discrepancy of revenue for the WETH-ALIEN vault is due to price error of the ALIEN token from 1inch oracle. I blacklisted ALIEN token from the 1inch oracle, and it now gets a price of 0 because no oracle has a valid price.

But there are still discrepancies in revenue/fees for a number of vaults. From what I can see, the "lifetime" fees of the aarakis frontend is likely wrong. I created two dune queries for fees from the [STG-USDC vault](https://dune.com/queries/2150743/3524896) and the [WETH-SNX vault](https://dune.com/queries/2150684). Dune numbers ($67k, $53k) are far from arrakis frontend ($0 and $35k) but close to our subgraph numbers ($67k, $53k).

> ### Cumulative Unique Users
> The daily and hourly cumulative unique user data do not match.
This doesn't seem to be a problem any more? https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Ftnkrxyz%2Farrakis-finance-optimism&tab=protocol&view=usageMetricsDailySnapshots-cumulativeUniqueUsers
 
> Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@tnkrxyz This QA is pretty old, so maybe there was something wrong then. I can't really find anything more on that specific point and could be that those vaults maybe did not load or the pools were inactive on the FE, but there is still assets in the contract. 

Sounds good about the pricing, looks like our TVL is slightly off compared to defiLlama on 02/08/2022, but looks like this is most likely from us pricing these [output tokens](https://api.thegraph.com/subgraphs/name/tnkrxyz/arrakis-finance-optimism/graphql?query=%7B%0A++vaultDailySnapshots+%28orderBy%3AtotalValueLockedUSD%2C+orderDirection%3A+desc%2C+where%3A%7Btimestamp_gte%3A+1644278400%2C+timestamp_lte%3A+1644364799%7D%29+%7B%0A++++vault+%7B%0A++++++name%0A++++++id%0A++++++inputToken+%7B%0A++++++++name%0A++++++++lastPriceUSD%0A++++++%7D%0A++++%7D%0A++++tot)
![arrakis-finance-optimism-030823](https://user-images.githubusercontent.com/107651107/223605544-66235e2c-80e0-4f87-b578-2fe551e5d551.jpeg)
alValueLockedUSD%0A++++outputTokenPriceUSD%0A++%7D%0A%7D) differently?

**Comment by tnkrxyz** [comment]
> Sounds good about the pricing, looks like our TVL is slightly off compared to defiLlama on 02/08/2022, but looks like this is most likely from us pricing these [output tokens](https://api.thegraph.com/subgraphs/name/tnkrxyz/arrakis-finance-optimism/graphql?query=%7B%0A++vaultDailySnapshots+%28orderBy%3AtotalValueLockedUSD%2C+orderDirection%3A+desc%2C+where%3A%7Btimestamp_gte%3A+1644278400%2C+timestamp_lte%3A+1644364799%7D%29+%7B%0A++++vault+%7B%0A++++++name%0A++++++id%0A++++++inputToken+%7B%0A++++++++name%0A++++++++lastPriceUSD%0A++++++%7D%0A++++%7D%0A++++totalValueLockedUSD%0A++++outputTokenPriceUSD%0A++%7D%0A%7D) differently? ![arrakis-finance-optimism-030823](https://user-images.githubusercontent.com/107651107/223605544-66235e2c-80e0-4f87-b578-2fe551e5d551.jpeg)

Given that the two lines track each other pretty well, it seems likely that the disrepancy is due to price. Taking a look rn.

**Comment by tnkrxyz** [comment]
@bye43 , Just to let you know that I am still working on this. Since Arrakis subgraph doesn't track underlying tokens, I need to add them before I can compare with defillama data.

**Comment by tnkrxyz** [comment]
> @tnkrxyz This QA is pretty old, so maybe there was something wrong then. I can't really find anything more on that specific point and could be that those vaults maybe did not load or the pools were inactive on the FE, but there is still assets in the contract. I would just ignore that QA point!
> 
> Sounds good about the pricing, looks like our TVL is slightly off compared to defiLlama on 02/08/2022, but looks like this is most likely from us pricing these [output tokens](https://api.thegraph.com/subgraphs/name/tnkrxyz/arrakis-finance-optimism/graphql?query=%7B%0A++vaultDailySnapshots+%28orderBy%3AtotalValueLockedUSD%2C+orderDirection%3A+desc%2C+where%3A%7Btimestamp_gte%3A+1644278400%2C+timestamp_lte%3A+1644364799%7D%29+%7B%0A++++vault+%7B%0A++++++name%0A++++++id%0A++++++inputToken+%7B%0A++++++++name%0A++++++++lastPriceUSD%0A++++++%7D%0A++++%7D%0A++++totalValueLockedUSD%0A++++outputTokenPriceUSD%0A++%7D%0A%7D) differently? 

@bye43 , sorry it took a while for me to get the bottom of this - I can confirm that the primary reason for the discrepancy with defillama is the price and, secondarily, our daily financial and market snapshots do not reflect on-chain data at the last moment of the day (i.e. these snapshots reflect earlier status rather than the last block, but they refresh and catch whenever an event handler is triggered). 

I create a [spreadsheet](https://docs.google.com/spreadsheets/d/1yxRKTPBKERT408HXfD8isCCL66fCgBu9GqLLFDz5Yug/edit?usp=sharing) that comparing on-chain data, defillama and [our subgraph](https://api.thegraph.com/subgraphs/name/tnkrxyz/arrakis-finance-optimism/graphql?query=query+MyQuery+%7B%0A++vaultDailySnapshots%28%0A++++skip%3A+0%0A++++first%3A+100%0A++++orderBy%3A+timestamp%0A++++orderDirection%3A+desc%0A++++where%3A+%7Btimestamp_lte%3A+1644364799%7D%0A++%29+%7B%0A++++id%0A++++timestamp%0A++++inputTokenBalance%0A++++outputTokenSupply%0A++++outputTokenPriceUSD%0A++++totalValueLockedUSD%0A++++_token0+%7B%0A++++++id%0A++++++name%0A++++++symbol%0A++++%7D%0A++++_token0Amount%0A++++_token0AmountUSD%0A++++_token1+%7B%0A++++++id%0A++++++name%0A++++++symbol%0A++++%7D%0A++++_token1Amount%0A++++_token1AmountUSD%0A++%7D%0A++vaults+%28orderBy%3A+createdTimestamp%29+%7B%0A++++id%0A++++createdTimestamp%0A++++_token0+%7B%0A++++++symbol%0A++++++lastPriceUSD%0A++++%7D%0A++++_token0Amount%0A++++_token0AmountUSD%0A++++_token1+%7B%0A++++++symbol%0A++++++lastPriceUSD%0A++++%7D%0A++++_token1Amount%0A++++_token1AmountUSD%0A++++%0A++%7D%0A%7D) for Feb 08, 2022 (see the comparision sheet). I had to change the schema and subgraph code to store token0 and token1 balances to make the comparison possible.  There is a difference of more than $713k between defillama tvl and ours (=~4%). However, if we switch to use defillama token price, the difference is reduced to $169k (or 0.96%). It is hard to tell which prices are better.

The remaining difference beside prices is that the underlying balances can change without any events emitted from the arrakis vault, for example, swaps in the corresponding uniswap pool. Because there is no events  from the vault, none of our handler is trigger and our data may be slightly outdated. One such example, is the sUSD/DAI vault (0x88ccDBbA89E073C5DC08B9c84dfc1fDc152c0dAc). On Feb 08, the daily snapshot still reflect the data when the last Burned event was emitted on Feb 04, with $52k of the underlying balances in DAI, however, swaps in the uniswap pool have shifted almost all DAI to sUSD. defillama and on-chain capture this change, but since no event was emitted from the vault, our subgraph data was not reflecting this change. If this is an issue, one possible solution is to update all vaults when an event triggers an update in any valut. It will make the data more up-to-date at the cost of performance. Let me know what you think.

**Comment by bye43** [comment]
@tnkrxyz thanks for the update! In terms of performance do you mean indexing speed or querying speed? If it is the former, I think we should make the trade-off for more accurate data, since this deployment is not critical atm. Also how much work would it be to implement your solution, I would also say if it is high lift then I would advise against it, as the TVL is not that large and the neither is the TVL difference

**Comment by tnkrxyz** [comment]
> @tnkrxyz thanks for the update! In terms of performance do you mean indexing speed or querying speed? If it is the former, I think we should make the trade-off for more accurate data, since this deployment is not critical atm. Also how much work would it be to implement your solution, I would also say if it is high lift then I would advise against it, as the TVL is not that large and the neither is the TVL difference

@bye43 , I meant the former (indexing/syncing speed) and it has no impact on querying speed - sorry for the confusion. This should be an easy implementation. I will work on this.
