### ISSUE TITLE
Yield Yak Avax QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1374]
## Review Info 
| Item| Info | 
| :----| :---| 
| Subgraph Reviewed  |	https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmVkmoHHXyojyoLpBRjjTvGBDJJQ6Uo3qdRTsAJYp3mWQM&tab=protocol |
| Date Reviewed  |	04-Nov-22 |
| Schema Version  |	1.2.0 |
| Subgraph Version  |	1.0.0 |
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1r9NxQbqiZ2OWUANtTSW9vCbdcrFgfPNQ/edit?usp=share_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL 

 - TVL data of subgraph is not matched with the official website data having a significant discrepancy of -72.90%. This is most likely due to the reason that 12 out of the top 20 pools from the official website are missing in the subgraph.
 - Refer to the sheet "Pool list (website)" for more info
 
 | Subgraph TVL| Official Website TVL | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 30,375,491.15| 52,519,759.00 | -22,144,268| -72.90%|

- Top 14th pool is named 'WETH.E-AVAX' in the official website but named 'JLP' in the subgraph. The pool shows a huge discrepancy.

| TVL OF 'WETH.E-AVAX' POOL | Official Website | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 1,154.09| 728,000.00 | -726,845.91| -62980.00%|

### Revenue

- Since there is a huge discrepancy in the TVL subgraph data against the official website and some large pools are missing in the subgraph, there is also a large discrepancy in revenue.  
 
 | Subgraph Daily Total Revenue| Revenue Computation using Official Website Data | Absolute Difference | % Difference | 
| :---- | :--- | :---  | :---  | 
| 33,405.44| 7,661.57 | -25,743.87| 336.01%|

 - See "Protocol" and "Revenue" sheets for more information

### Pool Snapshot

- All data in relation to revenue of each pool was not placed in the subgraph's Pool section. This applies to all top five pools.
- Missing data: dailySupplySideRevenueUSD, cumulativeSupplySideRevenueUSD. dailyProtocolSideRevenueUSD, cumulativeProtocolSideRevenueUSD, dailyTotalRevenueUSD, and cumulativeTotalRevenueUSD

### Usage metrics
- Daily transaction count is not in line with the sum of deposit and withdrawal count.  
-  Additionally, there are 131 active farms listed in the official website while more than 200 pools are listed in the subgraph with most of the latter having 0 TVL.

Please refer to the attached worksheet for more details.

**Comment by this-username-is-taken** [comment]
@koval1997

**Comment by bye43** [comment]
@koval1997 Let me know if you have any questions or there is anything you want to discuss. Here are some comments: 

- [ ] Yield aggregator schema - Looks like the subgraph is on YA schema 1.2.0, it should be on [1.3.0](https://github.com/messari/subgraphs/blob/master/schema-yield.graphql). Because subgraph is not on 1.3.0, `vaultDailySnapshots` are missing `dailySupplySideRevenueUSD`, `cumulativeSupplySideRevenueUSD`, `dailyProtocolSideRevenueUSD`, `cumulativeProtocolSideRevenueUSD`, `dailyTotalRevenueUSD`, and `cumulativeTotalRevenueUSD`

- [ ] `financialsDailySnapshots-totalValueLockedUSD` - The overall TVL looks off compared to [defiLlama](https://defillama.com/protocol/yield-yak-aggregator) and [token terminal](https://tokenterminal.com/terminal/projects/yield-yak). This looks like it might be from some vaults being missed in the subgraph, which I noted below. They also look like they start on 08/21/2021 and the [subgraph](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdB8VD5nUNTdrKkRqMYMopEgj2CiMGUePAuKukT5kjWBA&tab=protocol) starts on 12/12/2021. Overlay of the token terminal data compared to the subgraph:
![download-24](https://user-images.githubusercontent.com/107651107/209731485-1e85e0b8-ffd1-433a-9767-e6c318b1472a.jpg)

- [ ] `financialsDailySnapshots-dailySupplySideRevenueUSD` - This is 0 and it should be larger than `protocolSideRevenue` since it looks like yield yak splits revenue [10/90](https://docs.yieldyak.com/for-farmers/reinvest), supply side and protocol side respectively. It looks like right now all revenue is being counted as `protocolSideRevenue`

- [ ] Missing vaults - It looks vaults are missing from the [subgraph](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdB8VD5nUNTdrKkRqMYMopEgj2CiMGUePAuKukT5kjWBA&tab=poolOverview) compared to [yield yak UI](https://yieldyak.com/farms?tab=allFarms). Here is a list of addresses of some of the higher TVL vaults not being tracked:

| Vault Address |
|---|
|0xaAc0F2d0630d1D09ab2B5A400412a4840B866d95|
|0x8B414448de8B609e96bd63Dcf2A8aDbd5ddf7fdd|
|0x9f637540149f922145c06e1aa3f38dcDc32Aff5C|
|0x9414B6D2E0cAa55ddF727551C9Bd6304d7e7F6F3|
|0x22EDe03f1115666CF05a4bAfafaEe8F43D42cD56|
|0x01435466f844Fa957b48C41ea1d429b9BFAbd97d|
|0xeC6cCE7B9262048f656539330754216cC9481321|

- [ ] `RewardTokens` - It looks like `WAVAX` is being tracked as a reward token for [vaults](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdB8VD5nUNTdrKkRqMYMopEgj2CiMGUePAuKukT5kjWBA&tab=poolOverview). Per discord convo, yield yak does not have token rewards, so we can remove it as a reward token in the array then.

**Comment by Koval1997** [comment]
@bye43 Thank you very much for your comments. My colleague wrote questions in Telegram. Today I returned from vacation and will start fixing the calculations.

**Comment by dmelotik** [comment]
@Koval1997 Do you have any questions about this? Or do you have any blockers?

**Comment by this-username-is-taken** [comment]
No longer under development
