### ISSUE TITLE
Rethink subgraph versioning

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#1379]
Something @jaimehgb brought up was to rethink our  versioning process:

tl;dr
- it should be based on deployment expectations
- a #patch doesn't need to be redeployed
- a #minor could benefit from redeployment, but not critical
- a #major is critical that redeployment occurs
- This will be easier to know the status of current subgraphs and priority

Personally i am for this. Use this issue as a discussion board

**Comment by steegecs** [comment]
Nice! Thanks for putting up the issue.

**Comment by steegecs** [comment]
I like the structure as this is.

**Comment by bye43** [comment]
Also like the structure. To @steegecs point, I think maybe it would be good to think of minor and major in terms of protocol metrics/backfilling. For example, Uniswap V3 I would say `cumulativeUniqueUsers` is a minor change since we are not ingesting user metrics, but it would major when we do start displaying them. Obviously, this classification will not work all the time, but might be useful for initial framing. My other question is how is versioning going to relate to the versions of subgraphs we see (i.e. 1.2.1, etc). I think I generally am pretty lost when those versions change and what they signify.

**Comment by jaimehgb** [comment]
>  For example, Uniswap V3 I would say cumulativeUniqueUsers is a minor change since we are not ingesting user metrics, but it would major when we do start displaying them.

This is a good point. How do we know if a past minor change should be promoted to major? Feels like every minor change is a future major. If not, it should be a patch.

Maybe we can have some rule to not allow minor mismatches to persist for longer than X amount of time?

**Comment by bye43** [comment]
This looks good to me! Thanks @jaimehgb

**Comment by tnkrxyz** [comment]
Looks good to me too. I want to point out there may still be some subjective judgement involved in deciding between major and minor version, because we may not want to apply the 20% threshold on a few data points (e.g. in a hourly snapshot), on less critical/stable metrics (hypothetically difference in hourly active users, if any, will likely be large).

**Comment by dmelotik** [comment]
Second @tnkrxyz - I wouldn't put a number on it, but it is more of a judgement thing. TBH a major is probably something bad enough that we want to remove the protocol from PM until it is fixed

**Comment by dmelotik** [comment]
https://github.com/messari/subgraphs/pull/1659
