### ISSUE TITLE
GoldFinch Mainnet QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1409]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/benqi&tab=protocol
| Schema Version  |  2.0.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1zEFcUQmeER_TA7ukdBgFzrFhn2MQYn_K/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Supply Side and Protocol Side Revenue

- Supply side revenue must receive only about 90% of the daily total revenue as it is stated in the documentation of Goldfinch that the protocol retains 10% of the fees (interest payments) as reserves. 
- Data from Token Terminal also shows that 90% of the fees goes to the supply side.
- However, the subgraph data shows that 99% of the revenue gets received by the supply side.

| Subgraph - Nov. 10 Supply Side Revenue | Subgraph - Nov. 10 Daily Total Revenue | Supply Side Revenue to Daily Total Revenue % | 
| :---- | :--- | :---  | 
| 82,191.78| 82,426.92 | 99.71%| 

| Token Terminal - Nov. 10 Supply Side Revenue | Token Terminal - Nov. 10 Daily Total Revenue | Supply Side Revenue to Daily Total Revenue % | 
| :---- | :--- | :---  |
| 74,034.04| 82,495.37 | 89.74%| 

- Refer to the sheet 'Protocol'   

### Total Pool Count

The official website shows 24 pools as compared to subgraph's data of 23. 

### Pool Overview TVL and Rewards

- Out of the 24 pools in the subgraph, only one pool has a significant discrepancy of 80%. The pool is ranked 13th in the subgraph and the address is 0xd43a4f3041069c6178b99d55295b00d0db955bb5

|Subgraph's 13th pool TVL |Official website TVL data| % Difference |
| :---- | :--- | :---  | 
| 130,936.58 | 654,682.92 | -80.00%

- The first seven percentages under 'REWARD TOKENS' column are much smaller compared to GFI token reward percentages from the official website.
- Refer to the sheet "Pool_Overview" for details

### Pool Vault
- The reward APR data of the two biggest pools in the subgraph have a huge difference when compared to the official website's GFI reward APR data

|Pool ID | Subgraph Reward APR data| Official Website Reward APR data |
| :---- | :--- | :--- | 
| 0x8481a6ebaf5c7dabc3f7e09e44a89531fd31f822 | 12.49%  | 6.46% |

|Pool ID: | Subgraph Reward APR data | Official Website Reward APR data |
| :---- | :--- | :--- | 
| 0x00c27fc71b159a346e179b4a1608a0865e8a7470  | 0.35%  | 6.81% |

- Reward Token Emission data (rewardTokenEmissionsAmount and rewardTokenEmissionsUSD) of both pools might be incorrect as the implied GFI token prices are 53.80% and 59.13% lower than its market prices from CoinGecko.

|Pool ID |  Implied GFI token price | GFI token market price | % Difference |
| :---- | :--- | :---  |  :---  | 
| 0x8481a6ebaf5c7dabc3f7e09e44a89531fd31f822| 0.5005 | 0.76982 | 53.80% |

|Pool ID | Implied GFI token price |GFI token market price| % Difference |
| :---- | :--- | :---  |  :---  | 
| 0x00c27fc71b159a346e179b4a1608a0865e8a7470 | 0.4005 | 0.6373 | 59.13% |

- Refer to the sheet "Pool_vault schema" for details

Please refer to the attached worksheet for more details.

**Comment by ishraq8** [comment]
@tnkrxyz Great work. Seems like everything is fixed but there is a discrepancy between supply side revenue and protocol side revenue. See images. 

1) `supplysiderevenueUSD` says there is $53,409.7 on 2022-12-02 but on the same date `protocolsiderevenueUSD` shows zero. Also `protocolsiderevenueUSD` shows 0.117 on 2022-12-01 but `supplysiderevenueUSD` shows 0.

2) Another issue: 2022-05-11 shows 91,500.03 on `protocolsiderevenueUSD` but `supplysiderevenueUSD` shows 52,835. This is not adding up to the 90:10 ratio 

Using this subgraph: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/goldfinch 

![Image](https://user-images.githubusercontent.com/47088402/205509842-6f6771bc-e4dc-49db-953f-9c312798eed6.png)



![Image](https://user-images.githubusercontent.com/47088402/205509845-00178e70-0b65-4bd5-9c01-3b4e96af5f91.png)

**Comment by tnkrxyz** [comment]
@ishraq8 , Good observation & good question! 

Unlike a typical lending protocol that the protocol takes a fixed ratio of interest as protocol revenue, Goldfinch's protocol revenue comes from a number of different sources: 1.) withdraw fee from senior pool; 2.) interest earned from extra senior pool deposit swept (deposited) to Compound; 3.) a share the interest payment (even here it is not a fixed percentage, but depending on the senior & junior tranche, & interest remaining) from tranchedPools (the logic is a bit complicated, see https://github.com/goldfinch-eng/mono/blob/4ffb02ed3363fd658eb144b52e59340e44e0e104/packages/protocol/contracts/protocol/core/TranchedPool.sol#L475-L489). Because of this, the 90:10 split is an approximate over time, and may not be the case on a daily basis.

The revenue accounting is straightforward, as Goldfinch contracts emit `ReserveFundsCollected` event for protocol revenue, and `InterestCollected` for supply side revenue.

I cannot verify the 12-02 numbers as dune does not yet have data after 11-30, but for 2022-05-11, the number checks out:
- protocol side revenue (https://dune.com/queries/1705660): $92,488.90 (note there was a bug in the goldfinch subgraph that I have fixed, and increases protocol side revenue from $91,500.03; syncing in progress)
- supply side revenue (https://dune.com/queries/1705706): $52835.69

**Comment by ishraq8** [comment]
Hey @tnkrxyz thanks for this explanation. The revenue data looks good. However I think it might be worthwhile to add a small explainer at the beginning of the Goldfinch doc giving a high level explanation, so that users can refer to it to understand how the work was done. I just copied and pasted what you said below. Let me know what you think and I could create a PR or you can add it to yours. 

_Liquidity providers provide capital to the senior pool to generate yield.  In order to determine how to allocate capital from the Senior Pool, the protocol uses the novel principle of "trust through consensus." At a high level: when more Backers supply capital to a given Borrower Pool, the Senior Pool increases the ratio with which it adds leverage.

The protocol collects revenue in the senior pool from a number of sources including: 1) withdraw fee from senior pool; 2) interest earned from extra senior pool deposit swept (deposited) to Compound; 3) a share the interest payment_

**Comment by tnkrxyz** [comment]
@ishraq8 , I added a note for the ratio between protocol side revenue and supply side revenue in README: https://github.com/messari/subgraphs/pull/1298/commits/90d1953bba5da43d1344a2afecd37acdabf72800

Can you please review and let me know what you think?

**Comment by ishraq8** [comment]
@tnkrxyz Thank you for the addition to the docs. it looks great!

**Comment by ishraq8** [comment]
@tnkrxyz reopening this. Talked to @dmelotik, we think we may want to calculate APR for the senior pool (base rate is 0 but rate is derived from the jr pools). 

Could the APR be calculated based on the borrow:supply ratio? Also their docs have a formula: https://docs.goldfinch.finance/goldfinch/protocol-mechanics/liquidityproviders

We can discuss on discord as well. Thank you for all your work.

**Comment by bye43** [comment]
@ishraq8 is this addressed here - https://github.com/messari/subgraphs/issues/1499?

**Comment by ishraq8** [comment]
no here- https://github.com/messari/subgraphs/pull/1536

currently doing a QA almost done.

**Comment by ishraq8** [comment]
this looks good, rewards accurate and interest rate is fixed in senior pool
