### ISSUE TITLE
Build Arbitrum Bridge Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1410]
```[tasklist]
### Deployment QA Status
- [ ] https://github.com/messari/subgraphs/issues/2041
- [ ] Arbitrum: https://okgraph.xyz/?q=fortysevenlabs%2Farbitrum-one-bridge-arbitrum
```

**Comment by bye43** [comment]
@fortysevenlabs For the arbitrum deployment it looks like the majority of the metrics are exponential. See picture of the TVL below and looks like there is only one pool named `d` (this does not seem correct), which also has `$2,798,566,503,784,412,000,000,000,000` in TVL.
![Image](https://user-images.githubusercontent.com/107651107/234453011-ea2f1973-1e44-497e-861e-04308a44836c.png)
![Image](https://user-images.githubusercontent.com/107651107/234452993-2f9e112a-8f81-4cd1-98d5-cd5bf05f8b1c.jpeg)

**Comment by fortysevenlabs** [comment]
Discussing this issue on discord with @bye43 and @dmelotik.

**Observations**

* We were looking at current version of the subgraph instead of pending. Syncing takes month (or more) to complete.
* TVL would be 0 for L2 (since it's BURN_MINT on L2). Image below.
* Pools are being tracked accurately. Image below.

[Reference subgraph.messari.io link](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRnzNoNAmWxcTeVXCSyNw4b4YoMpd6Yswg8y68kRk7QQv&tab=pool&version=pending&name=fortysevenlabs/arbitrum-one-bridge-arbitrum).

**TVL (for Ether pool)**

<img width="2997" alt="image" src="https://github.com/messari/subgraphs/assets/4187512/8feb92b5-d28d-499b-9b1d-4a1edefbe95a">

**Pools**

<img width="1011" alt="image" src="https://github.com/messari/subgraphs/assets/4187512/2ac189bb-90ed-4441-a1e5-c2b08cbc144c">

**Comment by fortysevenlabs** [comment]
There was an indexing error for the arbitrum side of the subgraph. Resolved it [here](https://github.com/fortysevenlabs/messari-subgraphs/tree/arb-side-indexing-error)
