### ISSUE TITLE
Add Bastion Realms

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1415]
For example: https://app.bastionprotocol.com/realms/0xe1cf09BDa2e089c63330F0Ffe3F6D6b790835973

**Comment by dmelotik** [comment]
2 approaches: each one is a compound fork OR we add all of them onto the current bastion subgraph.

**Comment by bye43** [comment]
Deployment: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora&tab=poolOverview&overlay=https://api.thegraph.com/subgraphs/name/messari/bastion-protocol-aurora

@tnkrxyz Couple QA comments:

- [ ] Looks like `0x08ac1236ae3982ec9463efe10f0f320d9f5a9a4b` is for [staking `BSTN`](https://withdraw.bastionprotocol.com/kingdom/staking), so I believe we can remove this market since we do not usually count staked tokens as part of TVL. @dmelotik double checking this correct?
- [ ] For these markets `0xb76108eb764b4427505c4bb020a37d95b3ef5afe` and `0x4a45075d3e752f3676610fc427f5e6915ce63a63` it looks like the[ TVL is incorrect](https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora/graphql?query=%7B%0A++markets+%28where%3A+%7Bid_in%3A+%5B%220xb76108eb764b4427505c4bb020a37d95b3ef5afe%22%2C+%220x4a45075d3e752f3676610fc427f5e6915ce63a63%22%5D%7D%29+%7B%0A++++name%0A++++id%0A++++inputToken+%7B%0A++++++name%0A++++++id%0A++++++lastPriceUSD%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++%7D%0A%7D) compared to [Bastion UI](https://withdraw.bastionprotocol.com/realms/0xE550A886716241AFB7ee276e647207D7667e1E79), but the `inputTokenBalance` is correct, so might be a pricing issue. Interestingly, it looks like `0x07f9f7f963c5cd2bbffd30ccfb964be114332e30` the`stNear` token is priced correctly, but the TVL does not seem to = `inputTokenBalance * lastPriceUSD`. For `0x4a45075d3e752f3676610fc427f5e6915ce63a63`, `NEAR` looks like the price is incorrect (hardcoded at 1 maybe?) compared to[ Bastion UI](https://withdraw.bastionprotocol.com/realms/0xE550A886716241AFB7ee276e647207D7667e1E79).

**Comment by dmelotik** [comment]
@bye43 @tnkrxyz 

- In the technical sense the staking market is technically a market since it has the same contract code/deployment as any other compound market, but they just changed the risk params so that the deposits cannot be used for collateral and they subsidize the deposit interest rate. @bye43 with that knowledge, up to you if we include or not
- Also we are missing rewards for the new markets

**Comment by bye43** [comment]
@dmelotik 
- There is no borrows though right, so its just for governance/fees/BSTN inflation? I think if this is the case we should not count it as a market. 
- Ahh good catch. We would like to include those if possible @tnkrxyz

**Comment by tnkrxyz** [comment]
@bye43 , @dmelotik , thank you both for the QA! I am looking into them.

**Comment by tnkrxyz** [comment]
> * There is no borrows though right, so its just for governance/fees/BSTN inflation? I think if this is the case we should not count it as a market.

I will skip the BSTN market (will see if it has other side-effect).

> * Ahh good catch (added it to tasklist). We would like to include those if possible @tnkrxyz
Not sure whether rewards are not automatically enabled for the realm markets. checking.

Since the bastion PR hasn't merged yet. I will keep pushing to the PR and merging later. lmk if prefer to merge the PR now & create a separate PR for these tasks.

**Comment by dmelotik** [comment]
let's keep pushing to this. I will be OOO next week, but if you want to get it in. @jaimehgb can review the new changes from my last review

**Comment by tnkrxyz** [comment]
> @tnkrxyz Couple QA comments:
> 
> * [x]  Looks like `0x08ac1236ae3982ec9463efe10f0f320d9f5a9a4b` is for [staking `BSTN`](https://withdraw.bastionprotocol.com/kingdom/staking), so I believe we can remove this market since we do not usually count staked tokens as part of TVL. @dmelotik double checking this correct?
> * [x]  For these markets `0xb76108eb764b4427505c4bb020a37d95b3ef5afe` and `0x4a45075d3e752f3676610fc427f5e6915ce63a63` it looks like the[ TVL is incorrect](https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora/graphql?query=%7B%0A++markets+%28where%3A+%7Bid_in%3A+%5B%220xb76108eb764b4427505c4bb020a37d95b3ef5afe%22%2C+%220x4a45075d3e752f3676610fc427f5e6915ce63a63%22%5D%7D%29+%7B%0A++++name%0A++++id%0A++++inputToken+%7B%0A++++++name%0A++++++id%0A++++++lastPriceUSD%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++%7D%0A%7D) compared to [Bastion UI](https://withdraw.bastionprotocol.com/realms/0xE550A886716241AFB7ee276e647207D7667e1E79), but the `inputTokenBalance` is correct, so might be a pricing issue. Interestingly, it looks like `0x07f9f7f963c5cd2bbffd30ccfb964be114332e30` the`stNear` token is priced correctly, but the TVL does not seem to = `inputTokenBalance * lastPriceUSD`. For `0x4a45075d3e752f3676610fc427f5e6915ce63a63`, `NEAR` looks like the price is incorrect (hardcoded at 1 maybe?) compared to[ Bastion UI](https://withdraw.bastionprotocol.com/realms/0xE550A886716241AFB7ee276e647207D7667e1E79).
> * [X]  Include `BSTN` rewards for realm markets

@bye43 , I believe I have no addressed all the comments above. Brief explanation of what's happening

1. excluded BSTN market
2. the reason some of the price/TVL doesn't match is that the price oracles for the realm markets return relative prices. This is fine for realms including stable coins, but problems for the StNear realm, as the price of Near is always 1 and the price of stNear is relative to Near. This would also affects the TVL for other markets as we use token.lastPriceUSD. If the the Near market in the StNear realm is last to update price, other market would get incorrect price too. I fixed this by swapping the price oracle for the stNear realm to the corresponding tokens in the Hub or other realms.
3. Fixed. I cleaned up the hardcoded reward tokens and make the emission calculation more efficient (only needs to be updated when reward speed changes), but I could not get the price for one of reward token Meta, so it always gets 0 rewardEmissionsUSD.

The deployment is at https://thegraph.com/hosted-service/subgraph/tnkrxyz/bastion-protocol-aurora and dashboard https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora&tab=protocol . Please take a look when you get a chance and let me know if you find any problem.

I will wait till @dmelotik is back to review my new changes/fixes before I merge.

**Comment by tnkrxyz** [comment]
> @tnkrxyz The TVLs look good! Just quick couple things:
> 
> * [ ]  Looks like the [market is NOT ACTIVE](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora&tab=pool&poolId=0x4e8fe8fd314cfc09bdb0942c5adcc37431abdcd0) for this `0x4e8fe8fd314cfc09bdb0942c5adcc37431abdcd0`. Not sure if this is wrong or right, but the TVL seems pretty high for it to be inactive.

Good catch! Actually all markets in our subgraph are paused. It seems to me that it is a bug that affects all compound-forks subgraphs. In [`_handleActionPaused()`](https://github.com/messari/subgraphs/blob/22aeda2f47b73c55b573241a9ea0b789168aeeac/subgraphs/compound-forks/src/mapping.ts#L185-L189), it seems we should set `market.isActive = !pauseState` and `market.canBorrowFrom = !pauseState`. @dmelotik  should be able to confirm.

> * [ ]  The BSTN APR for the same market looks pretty high. I think this might be due to the pricing of `BSTN` looks like on [coinmarketcap `BSTN`](https://coinmarketcap.com/currencies/bastion-protocol/) is $0.0008067. And if you multiple that by the [`rewardsEmissionsAmount` ](https://api.thegraph.com/subgraphs/name/tnkrxyz/bastion-protocol-aurora/graphql?query=%7B%0A++market+%28id%3A+%220x4e8fe8fd314cfc09bdb0942c5adcc37431abdcd0%22%29+%7B%0A++++rewardTokens+%7B%0A++++++token+%7B%0A++++++++name%0A++++++++id%0A++++++++lastPriceUSD%0A++++++%7D%0A++++%7D%0A++++rewardTokenEmissionsAmount%0A++++rewardTokenEmissionsUSD%0A++%7D%0A%7D) 56,571.429 * 0.0008067 = $45.6 which is much smaller than the $191.402 reported

The issue here is that I am not updating the token price for reward emissions unless the reward speed changes in a market. I have added code to updateRewardTokenPrices inside handleAccrueInterest in [commit 
2792098](https://github.com/messari/subgraphs/pull/1805/commits/2792098c7d79be5dd435d7ecc71fa3cdad87dc98)
