### ISSUE TITLE
Liquity Ethereum Rewards

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1425]

**Comment by jaimehgb** [comment]
This is ready for review: https://okgraph.xyz/?q=QmSSafuj1YQ4aMCv6zxofF2L2cvUQ7acCjBBnmdDfbwELy

**Comment by bye43** [comment]
@pietydespises can you do a quick scan on this?

**Comment by pietydespises** [comment]
the "rewardAPR" graph in the "MarketDailySnapshots" section for the Stability Pool under the "Pool" tab looks off near the beginning (looks wrong is wrong). Any idea what's happneing here https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fid%2FQmSSafuj1YQ4aMCv6zxofF2L2cvUQ7acCjBBnmdDfbwELy&tab=pool&poolId=0x66017D22b0f8556afDd19FC67041899Eb65a21bb&view=marketDailySnapshots-rewardAPR 
? @jaimehgb everything else looks good!

**Comment by jaimehgb** [comment]
@pietydespises Seems to be because of LQTY price being pretty high on the day of launch:
<img width="854" alt="Screenshot 2022-12-03 at 21 16 13" src="https://user-images.githubusercontent.com/17258946/205470840-2475f19b-52e8-4a1d-b25a-6d4da546e2da.png”>

If daily emissions were 60,000, and price (from coingecko) was $73, that’s 4,380,000 daily USD reward emissions. Ours is at ~5.1M, slightly higher, which might be due to using the price at some point during the day instead of an average.

Do we want to replace the price at the day of launch with something more realistic? Or since it was the price at which it traded should we leave it as is? I can do either option :)

**Comment by jaimehgb** [comment]
Zooming in on that day gives even crazier prices:
<img width="292" alt="Screenshot 2022-12-03 at 21 25 29" src="https://user-images.githubusercontent.com/17258946/205470999-e0686aa9-7726-4188-9df3-082301503c68.png">

**Comment by pietydespises** [comment]
this makes sense! I think it's ok to leave it in as is, users will be able to see a more sensible graph as long as their timeline isn't set to "All"
