### ISSUE TITLE
Abracadabra Arbitrum: subgraph stopped syncing

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1500]
Indexing errors on abracadabra

arbitrum: 44305314

**Comment by MichaelC1999** [comment]
Just commented this on an open Abra-avax issue, but posting it here since it looks to affect Abra-arb as well

Abracadabra Arbitrum marketDailySnapshots do not have any data in the rate fields, regardless of which market.

https://api.thegraph.com/subgraphs/name/messari/abracadabra-money-arbitrum/graphql?query=%7B%0A++markets+%7B%0A++%09dailySnapshots+%28first%3A+1%29+%7B%0A++++++id%0A++++%09rates+%7B%0A++++++%09id%0A++++%09%7D%0A++++%7D%0A++++hourlySnapshots+%28first%3A+1%29+%7B%0A++++++rates+%7B%0A++++++++id%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D

**Comment by bye43** [comment]
This is on the graph side looks like its fixed now. I moved the 0 `marketDailySnapshots` to this issue: https://github.com/messari/subgraphs/issues/1293. Going to close this
