### ISSUE TITLE
MakerDAO Ethereum: dailyLiquidateUSD and dailyLiquidateCount potential issues

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1502]
It looks like the MakerDAO revenue for 12/06/2022 is extremely high (~$30m) because the subgraph is recording roughly ~$220m in liquidations for USDC-A vault on that day. It looks like MakerDAO was liquidating the USDC-A vault for any collateral that was [under 101% ](https://twitter.com/Risk_DAO/status/1600488976749559808). In comparison to https://maker.blockanalitica.com/liquidations/?tab=per-date it looks like we are overestimating the amountUSD and liquidation count. IIRC we have slight differences based on the timestamp we track for liquidations, but even if you account for 12/05 and 12/07 our values looks too high. [Query](https://api.thegraph.com/subgraphs/name/messari/makerdao-ethereum/graphql?query=%7B%0A++marketDailySnapshots+%28orderBy%3A+dailyLiquidateUSD%2C+orderDirection%3Adesc%2C+where%3A+%7Btimestamp_gte%3A+1670284800%2C+timestamp_lte%3A+1670371199%7D%29+%7B%0A++++timestamp%0A++++market+%7B%0A++++++name%0A++++++id%0A++++%7D%0A++++dailyLiquidateUSD+%0A++++dailyProtocolSideRevenueUSD%0A++%7D+%0A%7D) for liquidations for USDC-A.

**Comment by tnkrxyz** [comment]
I believe the difference between the number in our subgraph and blockanalitica number is they do not include a subset of the liquidations (looks like they are liquidated at a loss to the protocol). For example, liquidation # 11:

![image](https://user-images.githubusercontent.com/97625120/206319458-a1617758-ca54-47c3-9335-d8fbba7fbe81.png)

https://maker.blockanalitica.com/liquidations/USDC-A/11/

https://etherscan.io/tx/0xe08f9e75afe6dd023ef1c08b5058c67c532ad96a0c531305734e6c27a8f3a855#eventlog

Those liquidations amount to ~$21m: https://docs.google.com/spreadsheets/d/1_6Ra27FIypoEyouiPVXtgVt8gJcWx69P8i_QLWt2JDA/edit?usp=sharing

I think the total liquidation numbers match after including the excluded liquidations.

Your question does bring up another (old) issue about protocol side revenue - whether we should set negative protocol revenue when collateral is sold at a loss (less than the debt). Makerdao had a similar issue in March 2020 (https://insights.glassnode.com/what-really-happened-to-makerdao/). I believe our decision was to keep calculating protocol side revenue using the penalty fee %, instead of accounting a loss to the protocol, but we may want to revisit this at some point.

**Comment by bye43** [comment]
Fixed bug that was ignoring liquidation penalty when it was set to 0

**Comment by bye43** [comment]
Going to leave this open till change is deployed on decentralized network

**Comment by tnkrxyz** [comment]
> Going to leave this open till change is deployed on decentralized network

@bye43 Shall we create a separate issue or use #1521 for this? It makes anxious to have a p0 task assigned to me remain open :laughing:

**Comment by bye43** [comment]
Ahh, gotcha - I'll close the issue and leave it here then and remove the tag if thats ok?
