### ISSUE TITLE
Add support for more OHM liquidity pools in Sushi and Balancer subgraphs

### ISSUE THREAD

**Issue by EdgeCaser** [messari/subgraphs#1629]
We are trying to get a complete view of the status of the Olympus protocol liquidity pools. Unfortunately, some of the most relevant pools are currently not captured by the Sushiswap and Balancer subgraphs.

**Describe the solution you'd like**
Please add the following contracts to the respective subgraphs:

 Sushiswap:
- SushiSwap OHM V2-DAI Liquidity Pool `0x055475920a8c93CfFb64d039A8205F7AcC7722d3`

Balancer:

- Balancer V2 OHM-WETH Liquidity Pool  `0xd1ec5e215e8148d76f4460e4097fd3d5ae0a3558`
- Balancer V2 OHM-DAI Liquidity Pool `0x76fcf0e8c7ff37a47a799fa2cd4c13cde0d981c9`
- Balancer V2 BTRFLY-OHM LP `0x2de32a7c98c3ef6ec79e703500e8ca5b2ec819aa`
- Balancer V2 Bond-OHM `0xf5f6fb82649df7991054ef796c39da81b93364df`
- Balancer V2 wETH-FDT Liquidity Pool  `0xfb46bc8fc0d06421d362a31b7230f39462efa79a`

**Describe alternatives you've considered**
I have searched for other subgraphs that could hold this data, but I have not found them. I also appreciate standardized schemas, so being able to pull everything from one spot would be ideal.

Thanks!

**Comment by bye43** [comment]
Hi @EdgeCaser! I am getting queries back from the subgraphs for those pools:

- [SushiSwap OHM V2-DAI Liquidity Pool 0x055475920a8c93CfFb64d039A8205F7AcC7722d3](https://api.thegraph.com/subgraphs/name/messari/sushiswap-ethereum/graphql?query=%7B%0A++liquidityPool+%28id%3A+%220x055475920a8c93cffb64d039a8205f7acc7722d3%22%29+%7B%0A++++name%0A++++totalValueLockedUSD%0A++%7D%0A%7D)

- [All Balancer pools](https://api.thegraph.com/subgraphs/name/messari/balancer-v2-ethereum/graphql?query=%7B%0A++liquidityPools+%28where%3A+%7Bid_in%3A+%5B%220xd1ec5e215e8148d76f4460e4097fd3d5ae0a3558%22%2C+%220x76fcf0e8c7ff37a47a799fa2cd4c13cde0d981c9%22%2C+%220x2de32a7c98c3ef6ec79e703500e8ca5b2ec819aa%22%2C+%220xf5f6fb82649df7991054ef796c39da81b93364df%22%2C+%220xfb46bc8fc0d06421d362a31b7230f39462efa79a%22%5D%7D%29+%7B%0A++++name%0A++++id%0A++++totalValueLockedUSD%0A++++inputTokens+%7B%0A++++++name%0A++++++id%0A++++++lastPriceUSD%0A++++%7D%0A++%7D%0A%7D)

It looks like for the sushiswap pool it may be because the contract address is not in all lowercase. Also quick note, there was a mispricing for a token pair on that Balancer deployment earlier this week, which cause the TVL to spike. There is a new deployment pending and it doesn't look like it affected any of the pools above, but just incase your using protocol snapshots too.

**Comment by EdgeCaser** [comment]
d'oh! Thanks a lot for the help.
