### ISSUE TITLE
cBridge Mainnet QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1663]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-ethereum&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/19HyoalZh_XmmodkyqX7qeiZxPR5e062i/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  TVL

The recent subgraph TVL data is not mathematically in line with both Defi Llama's and the official website's data as it shows a massive discrepancy of 1653.42% and 5922.86%. 

January 27, 2023:

| Subgraph - TVL | Defi Llama - TVL | Absolute difference | Difference % |
| :---- | :--- | :---  | :---  | 
| 1,556,047,420.16| 89,228,040.12 | 1,466,819,380.04| 1643.90%| 

| Subgraph - TVL | Official Website - TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 1,556,047,420.16| 25,835,697.00 | 1,530,211,723.16| 5922.86%| 

- Refer to the sheet 'Protocol'   

###  Revenue

- Based on cBridge protocol's documentation, all fees go to the protocol side. 
- The daily total revenue must also not be zero in the recent data. We computed the implied revenue using the data from the official website and the results show that the daily total revenue for January 27 of 2023 should be around $3,725. 

January 27, 2023:
| Subgraph - Daily Total Revenue | Official Website - Daily Total Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 0.00| 25,835,697.00 | 3725.175| -100.00%| 

- See the 'Protocol' and 'Support-Implied-Revenue-and-TVL' sheets for more information.

### Total Pool Count

- The official website only shows 34 instead of 116 pools
- Refer to the sheet 'Protocol'   

### Total Supported Token Count

- According the official website's analytics, cBridge on Mainnet supports 109 tokens instead of 104.
- Refer to the sheet 'Protocol'   

### Pool Overview - TVL and Rewards

- The TVL data of the top 10 pools have massive discrepancies ranging from 65% to 430,067% with the official website data. Here are TVL comparisons of the top 3 pools:

| Subgraph - USDC Pool TVL | Official Website - USDC Pool TVL | Difference % 
| :---- | :--- | :---  | 
| 665,447,235.35| 5,808,452.00 | 11,356.53%| 

| Subgraph - USDT Pool TVL | Official Website - USDT Pool TVL | Difference % 
| :---- | :--- | :---  | 
| 451,021,083.51| 6,454,898.00 | 6,887.27%| 

| Subgraph - WETH Pool TVL | Official Website - WETH Pool TVL | Difference % 
| :---- | :--- | :---  | 
| 377,182,167.01| 2,349,719.00 | 15,952.22%| 

- The data on the 'Reward Tokens' is most likely incorrect too due to the large discrepancies in TVL data.
- Refer to the sheet "Pool_Overview" for details

## Editorials  

There are some errors we have noticed and are not necessarily data errors.

### Pool

- The Pool section is not showing any data and only shows black screen.
- Refer to the sheet 'Pool_vault_schema' and 'Pool_snapshots'  

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@tnkrxyz cbridge QA for ETH

**Comment by tnkrxyz** [comment]
# WIP (will update once finished)

Thanks for the QA! I am responding below to each specific issue.

> ## Metrics to Review
> ### TVL
> The recent subgraph TVL data is not mathematically in line with both Defi Llama's and the official website's data as it shows a massive discrepancy of 1653.42% and 5922.86%.
> 
> January 27, 2023:
> 
> Subgraph - TVL	Defi Llama - TVL	Absolute difference	Difference %
> 1,556,047,420.16	89,228,040.12	1,466,819,380.04	1643.90%
> Subgraph - TVL	Official Website - TVL	Absolute difference	Difference %
> 1,556,047,420.16	25,835,697.00	1,530,211,723.16	5922.86%
> * Refer to the sheet 'Protocol'

I am looking into this - one likely explanation is that we include the PegToken bridge v1 and v2 in addition to the liquidity-pool based cbridge.

> ### Revenue
> * Based on cBridge protocol's documentation, all fees go to the protocol side.
> * The daily total revenue must also not be zero in the recent data. We computed the implied revenue using the data from the official website and the results show that the daily total revenue for January 27 of 2023 should be around $3,725.
>
> January 27, 2023:
> 
> Subgraph - Daily Total Revenue	Official Website - Daily Total Revenue	Absolute difference	Difference %
> 0.00	25,835,697.00 (?)	3725.175	-100.00%

Fees from the liquidity-pool-based cbridge is splitted between LP and the bridge (https://cbridge-docs.celer.network/reference/faq#what-is-the-commission-rate-in-the-sgn). Since we can only track when the fees are withdrawn from the cbridge contract (the fee varies by token/chain and is implemented in their SGN code, not on-chain), fee in our subgraph is more jumpy than daily accrued amount.

> * See the 'Protocol' and 'Support-Implied-Revenue-and-TVL' sheets for more information.
> 
> ### Total Pool Count
> * The official website only shows 34 instead of 116 pools
> * Refer to the sheet 'Protocol'

Because the bridge schema only allows us to track one input token per pool (market), we have to split the liquidity-based pool into many markets/pools, one token per market, plus the OriginalVaultToken/PeggedToken market.
 
> ### Total Supported Token Count
> * According the official website's analytics, cBridge on Mainnet supports 109 tokens instead of 104.
> * Refer to the sheet 'Protocol'

Looking into this. My hypothsis atm is that since we only create a new token/market when there is deposit/transfer. There may be active markets/tokens without any activity yet.

> 
> ### Pool Overview - TVL and Rewards
> * The TVL data of the top 10 pools have massive discrepancies ranging from 65% to 430,067% with the official website data. Here are TVL comparisons of the top 3 pools:
> 
> Subgraph - USDC Pool TVL	Official Website - USDC Pool TVL	Difference %
> 665,447,235.35	5,808,452.00	11,356.53%
> Subgraph - USDT Pool TVL	Official Website - USDT Pool TVL	Difference %
> 451,021,083.51	6,454,898.00	6,887.27%
> Subgraph - WETH Pool TVL	Official Website - WETH Pool TVL	Difference %
> 377,182,167.01	2,349,719.00	15,952.22%
> * The data on the 'Reward Tokens' is most likely incorrect too due to the large discrepancies in TVL data.
> * Refer to the sheet "Pool_Overview" for details

Looking into this.
 
> ## Editorials
> There are some errors we have noticed and are not necessarily data errors.
> 
> ### Pool
> * The Pool section is not showing any data and only shows black screen.
Likely a frontend error I sometimes ran into myself.

> * Refer to the sheet 'Pool_vault_schema' and 'Pool_snapshots'

 
> Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@pietydespises @tnkrxyz Addressed this feedback. Do you mind reviewing and if it looks good just quickly scanning all the other deployments in the PR attached to the issue (linked Pull Requests in the top right)

**Comment by pietydespises** [comment]
@tnkrxyz These updates for Ethereum look good, but getting deployment errors for the other chains. Could you get a look when you get a chance?

**Comment by tnkrxyz** [comment]
> @tnkrxyz Looks like some the deployments besides ETH failed to sync here and I am getting an error `DEPLOYMENT ERROR - https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-arbitrum does not have any "protocol" entities. Essential data that determines validation can not be pulled without this entity.` on the dashboard. Are the deployment links for the other networks correct in the PR. Thanks!

Yap, cbridge-arbitrum crashed for odd/unexpected error before it went far. Will look into this after I fix makerdao + euler (which I assume is higher priority since they are deployed subgraphs).

**Comment by bye43** [comment]
@tnkrxyz Sounds good, thanks! I agree with those priorities. @pietydespises The rest of those deployments looks like they are synced and working if you don't mind quickly scanning them like you did for Stargate

**Comment by pietydespises** [comment]
These look good, though BSC, GNOSIS, and MOONRIVER are still failing. Any idea what's happening there @tnkrxyz ?

Just a note, we're also going to have to add a tooltip to explain why all the revenue graphs look as spiky as they do (explained above), though I believe they're quantitatively correct

**Comment by tnkrxyz** [comment]
> 



> These look good, though BSC, GNOSIS, and MOONRIVER are still failing. Any idea what's happening there @tnkrxyz ?

Oops, haven't looked at them after deployed. Fixed (hopefully) and re-deployed. I still need to fix arbitrum, which is a stranger error.

> Just a note, we're also going to have to add a tooltip to explain why all the revenue graphs look as spiky as they do (explained above), though I believe they're quantitatively correct

That'll be great.

**Comment by tnkrxyz** [comment]
@pietydespises , both are due to careless mistake of mine. Now fixed and redeployed.

- status
   - https://thegraph.com/hosted-service/subgraph/tnkrxyz/cbridge-moonriver?version=pending
   - https://thegraph.com/hosted-service/subgraph/tnkrxyz/cbridge-gnosis?version=pending

available at the same dashboard links once synced.

**Comment by pietydespises** [comment]
@tnkrxyz the data looks very strange for both these protocols please have a look. It could be correct because I doubt these chains ever get bridged onto, but just want to make sure there's not a programming bug. For instance gnosis only has data for two dates.

**Comment by tnkrxyz** [comment]
@pietydespises , interesting. It seems cbridge-gnosis is actually ghosted. There have been only three events (transactions) of interest since contract deployment:
1. one Send() event on pool-based bridge: https://gnosisscan.io/tx/0x08dc7e43ca172ba8582fe51dc7fe6eef8419b22e0cb7c8f7eb5df074507b633d
2. Two Mint() event on pegged token bridge: https://gnosisscan.io/tx/0x0af039061571229cf2098c13246e6e5c92d4afbe041447d91eb7fb2020a09cd2 and https://gnosisscan.io/tx/0x95d7b84c0de93847a602939435b3460524b4e54b50f8613a110bd4e29bc0a47d

**Comment by pietydespises** [comment]
all good, theyre small chains anyway

**Comment by bye43** [comment]
@tnkrxyz @pietydespises Just want to confirm that these deployments have 0 TVL and we will not show on the Messari FE for now:

- Boba
- Celo
- Gnosis
- Moonbeam
- Moonriver

I saw the comments on Moonbeam [here](https://github.com/messari/subgraphs/pull/1573#issuecomment-1499904889), but when I was looking at the deployment it looks like there is no revenue there. Please let me know if the TVL for those deployments are correct. Thanks

**Comment by tnkrxyz** [comment]
@bye43 , except for Celo and gnosis, other chains([Boba](https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-boba/graphql?query=query+MyQuery+%7B%0A++poolDailySnapshots+%28orderBy%3AinputTokenBalance+orderDirection%3A+desc%29+%7B%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++++cumulativeVolumeIn%0A++++cumulativeVolumeOut%0A++%7D%0A++financialsDailySnapshots%28orderBy%3A+dailyVolumeInUSD%2C+orderDirection%3A+desc%29+%7B%0A++++dailyNetVolumeUSD%0A++++dailyVolumeInUSD%0A++++dailyVolumeOutUSD%0A++++totalValueLockedUSD%0A++%7D%0A%0A%7D), [Moonbeam](https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-moonbeam/graphql?query=query+MyQuery+%7B%0A++poolDailySnapshots+%28orderBy%3AinputTokenBalance+orderDirection%3A+desc%29+%7B%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++++cumulativeVolumeIn%0A++++cumulativeVolumeOut%0A++%7D%0A++financialsDailySnapshots%28orderBy%3A+dailyVolumeInUSD%2C+orderDirection%3A+desc%29+%7B%0A++++dailyNetVolumeUSD%0A++++dailyVolumeInUSD%0A++++dailyVolumeOutUSD%0A++++totalValueLockedUSD%0A++%7D%0A%0A%7D), and [Moonriver](https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-moonriver/graphql?query=query+MyQuery+%7B%0A++poolDailySnapshots+%28orderBy%3AinputTokenBalance+orderDirection%3A+desc%29+%7B%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++++cumulativeVolumeIn%0A++++cumulativeVolumeOut%0A++%7D%0A++financialsDailySnapshots%28orderBy%3A+dailyVolumeInUSD%2C+orderDirection%3A+desc%29+%7B%0A++++dailyNetVolumeUSD%0A++++dailyVolumeInUSD%0A++++dailyVolumeOutUSD%0A++++totalValueLockedUSD%0A++%7D%0A%0A%7D)) all have non-zero inputTokenBalance. They have $0.0 TVL because we don't have price for any of the tokens being transfered on those chains. 

Even cBridge on celo has 0 TVL, it does have [transfers (from burn-mint transfers)](https://api.thegraph.com/subgraphs/name/tnkrxyz/cbridge-celo/graphql?query=query+MyQuery+%7B%0A++poolDailySnapshots+%28orderBy%3AinputTokenBalance+orderDirection%3A+desc%29+%7B%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++inputTokenBalance%0A++++totalValueLockedUSD%0A++++cumulativeVolumeIn%0A++++cumulativeVolumeOut%0A++%7D%0A++financialsDailySnapshots%28orderBy%3A+dailyVolumeInUSD%2C+orderDirection%3A+desc%29+%7B%0A++++dailyNetVolumeUSD%0A++++dailyVolumeInUSD%0A++++dailyVolumeOutUSD%0A++++totalValueLockedUSD%0A++%7D%0A%0A%7D). gnosis is the only chain where cbridge contracts have no transfer activity or TVL. I will let you decide whether it makes sense to exclude them from messari FE.

In term of revenue, I believe @pietydespises 's comment on moonbeam and revenue are separate from each other and he was not implying there is revenue in cBridge moonbeam (@pietydespises, feel free to clarify if I am mistaken here). It is likely non-zero in reality, but again because we don't have price oracle on the moonbeam chain, any revenue multiplying with price of 0 gives us 0.
