### ISSUE TITLE
Build Opyn Subgraph 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1665]
```[tasklist]
### Deployment Status
- [ ] https://github.com/messari/subgraphs/issues/1981
- [x] Arbitrum: https://okgraph.xyz/?q=spitko/opyn-gamma-arbitrum
- [x] Avalanche: https://okgraph.xyz/?q=spitko%2Fopyn-gamma-avalanche
- [x] Polygon: https://okgraph.xyz/?q=spitko%2Fopyn-gamma-polygon
```

**Comment by bye43** [comment]
@spitko

**Comment by bye43** [comment]
Waiting for: https://github.com/messari/subgraphs/issues/1963 to merge before QA

**Comment by bye43** [comment]
Ethereum QA: https://github.com/messari/subgraphs/issues/1981

**Comment by bye43** [comment]
@ishraq8 Looks like ETH was good! If you can give the rest of these deployments a quick scan, then we can close out Opyn as done/`prod`

**Comment by ishraq8** [comment]
<img width="805" alt="Screen Shot 2023-04-12 at 2 24 11 PM" src="https://user-images.githubusercontent.com/47088402/231550419-2de91e36-0917-45e6-b222-e3a7b930f510.png">

Getting this error in okgraph, looks like related to new entities in schema @spitko @dmelotik

**Comment by spitko** [comment]
> Getting this error in okgraph, looks like related to new entities in schema @spitko @dmelotik

Redeployed, should be fine now.

**Comment by ishraq8** [comment]
Just a couple of questions @spitko from the QA:

1) TVL looks a bit off compared to defillama. 
<img width="477" alt="Screen Shot 2023-04-14 at 9 31 43 AM" src="https://user-images.githubusercontent.com/47088402/232057832-ebb769bf-f4fe-44b4-a982-20
<img width="475" alt="Screen Shot 2023-04-14 at 9 32 11 AM" src="https://user-images.githubusercontent.com/47088402/232057884-58519e1c-f812-470b-a515-cefc97f02564.png">
dbe24ed4c4.png">
<img width="377" alt="Screen Shot 2023-04-14 at 9 32 26 AM" src="https://user-images.githubusercontent.com/47088402/232057900-98cde4c9-faa0-4d9d-ad2d-0b289d00e8e3.png">

2) What is the logic behind null revenue? Is it because all options are cash settled and basically value of underlying is just transferred between parties. Just want to confirm.

3) Arbitrum is new, if the other two are accurate Arbitrum should be when launched.

**Comment by spitko** [comment]
> Just a couple of questions @spitko from the QA:
> 
> 1. TVL looks a bit off compared to defillama.

DefiLlama data is not including MaticX. Subgraph TVL matches contract holdings: https://polygonscan.com/address/0x30ae5debc9edf60a23cd19494492b1ef37afa56d

> 2. What is the logic behind null revenue? Is it because all options are cash settled and basically value of underlying is just transferred between parties. Just want to confirm.

There is no percentage fee taken by Opyn.

**Comment by ishraq8** [comment]
Opyn QA passed, the protocol has no revenue, overview of how it works. 
![1_-qwbokj2s9junyx2zztr2q](https://user-images.githubusercontent.com/47088402/232808519-280c3d41-f446-4473-85da-19a9c7b0da4a.png)

**Comment by dmelotik** [comment]
Deployed all to hosted. Need to deploy ethereum to dec
