### ISSUE TITLE
MakerDAO subgraph features

### ISSUE THREAD

**Issue by schmidsi** [messari/subgraphs#1672]
- Ilks should contain fields to say if they are still active? 
- Ilk name (ETH-A) (derived from bytes32 Ilk: https://etherscan.io/address/0xdc26c9b7a8fe4f5df648e314ec3e6dc3694e6dd2#readContract)
- Store raw kick & take events (https://maker.blockanalitica.com/liquidations/ETH-A/840/)
-

**Comment by bye43** [comment]
@schmidsi Do you mind expanding on these bullets? I am not sure I am following also what does "ilks" mean, sorry not familiar with that acronym. Thanks!

**Comment by schmidsi** [comment]
@bye43, sure and sorry. This was mainly my notes during a call with them. So Ilk's are basically the vault types on the MakerDAO protocol. ETH-A/DAI, ETH-B/DAI, WBTC-A/DAI, etc. They are already in the schema here: https://github.com/messari/subgraphs/blob/master/subgraphs/makerdao/schema.graphql#L1269

- Not all Ilks are still active as far as I understand, so we should add a field on that entity that indicates if the Ilk is still active. This is most probably the "live" function here: https://etherscan.io/address/0xdc26c9b7a8fe4f5df648e314ec3e6dc3694e6dd2#readContract
- Ilks also have a human readable name. It is hidden below a bytes32. On that Etherscan page, there is the "ilk" Bytes32 field, which resolves to `0x554e495632574254434554482d41000000000000000000000000000000000000` which translates to "UNIV2WBTCETH-A" as a string.
- Kick & Take events are events emitted by the Maker Protocol when liqudations happen. First a kick, followed by a take. For anybody interested in liquidations on Maker, making this distinguishion is crucial.

Let me know if I can expand more

**Comment by bye43** [comment]
Gotcha. Does our current implementation not track the first couple of bullets i.e. for the vault example above we can return the name of the vault and if its active or not in this [query](https://api.thegraph.com/subgraphs/name/messari/makerdao-ethereum/graphql?query=%7B%0A++market+%28id%3A+%220x2f0b23f53734252bda2277357e97e1517d6b042a%22%29+%7B%0A++++name%0A++++isActive%0A++%7D%0A%7D)? If not, will let @tnkrxyz answer since he built the maker subgraph!

**Comment by tnkrxyz** [comment]
> @bye43, sure and sorry. This was mainly my notes during a call with them. So Ilk's are basically the vault types on the MakerDAO protocol. ETH-A/DAI, ETH-B/DAI, WBTC-A/DAI, etc. They are already in the schema here: https://github.com/messari/subgraphs/blob/master/subgraphs/makerdao/schema.graphql#L1269
> 
> * Not all Ilks are still active as far as I understand, so we should add a field on that entity that indicates if the Ilk is still active. This is most probably the "live" function here: https://etherscan.io/address/0xdc26c9b7a8fe4f5df648e314ec3e6dc3694e6dd2#readContract
> * Ilks also have a human readable name. It is hidden below a bytes32. On that Etherscan page, there is the "ilk" Bytes32 field, which resolves to `0x554e495632574254434554482d41000000000000000000000000000000000000` which translates to "UNIV2WBTCETH-A" as a string.
> * Kick & Take events are events emitted by the Maker Protocol when liqudations happen. First a kick, followed by a take. For anybody interested in liquidations on Maker, making this distinguishion is crucial.
> 
> Let me know if I can expand more

@schmidsi , thanks for the comments/suggestions. Entities with a "_" prefix, like the _Ilk entity, are helper entities we don't expect users to query. Each _Ilk entry maps to a market entry - you can also find the name and status (active true/false) there: https://api.thegraph.com/subgraphs/name/tnkrxyz/makerdao-ethereum/graphql?query=query+MyQuery+%7B%0A++markets+%7B%0A++++id%0A++++name%0A++++isActive%0A++++canBorrowFrom%0A++%7D%0A++liquidates+%7B%0A++++id%0A++++asset+%7B%0A++++++id%0A++++++symbol%0A++++%7D+++%0A++++amount%0A++++hash%0A%09%09blockNumber%0A++%7D%0A%7D

We derive our liquidation events from Kick and Take (as well as Bite from the old Cat contract), but since they are unique to Marker and we have not track these events. Both are straightforward to add.
