### ISSUE TITLE
Build Livepeer Subgraph

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1723]
@ishraq8 Link for QA here:
 
Deployment Status:
- [x] Ethereum: https://okgraph.xyz/?q=QmbHKjxkFDvyk5a259AdSRELBRSMk48CLsy6f9F9DBeuKs

**Comment by bye43** [comment]
@shashwatS22 @'ing you for tracking

**Comment by ishraq8** [comment]
We are building anew schema for this will update once I get it

**Comment by ishraq8** [comment]
@shashwatS22 We have a PR for a new schema for web3 infra/Depin once that it through LivePeer will be the first on that schema: https://github.com/messari/subgraphs/pull/1741

Also some comments from our data scientist @jacubcub:

1) For LivePeer the protocol collects revenue in ETH and not in their native LPT. For fields that are `RevenueToken` denominate in ETH since protocol revenue not in LPT.

2) Some notes from the already existing LivePeer subgraph, than may be useful to you: 

Found the code for that api https://github.com/livepeer/explorer/blob/main/pages/api/usage.tsx

looks like they are querying their subgraph and then doing some transformations (they use time travel queries to get much of the historical data, but there is also a `days` entity in their subgraph which has historical data for some fields)

This is where the queries are defined https://github.com/livepeer/explorer/blob/main/apollo/subgraph.ts

You can see how they do the minutes calculation in `usage.tsx` too. It’s based off of fees and a constant pixels per minute that they get from assuming a certain distribution of transcoded frame rates and resolutions. Then they add minutes from livepeer.com usage api which is not public: https://livepeer.com/api/usage

**Comment by shashwatS22** [comment]
> @shashwatS22 We have a PR for a new schema for web3 infra/Depin once that it through LivePeer will be the first on that schema: #1741
> 
> Also some comments from our data scientist @jacubcub:
> 
> 1. For LivePeer the protocol collects revenue in ETH and not in their native LPT. For fields that are `RevenueToken` denominate in ETH since protocol revenue not in LPT.
> 2. Some notes from the already existing LivePeer subgraph, than may be useful to you:
> 
> Found the code for that api https://github.com/livepeer/explorer/blob/main/pages/api/usage.tsx
> 
> looks like they are querying their subgraph and then doing some transformations (they use time travel queries to get much of the historical data, but there is also a `days` entity in their subgraph which has historical data for some fields)
> 
> This is where the queries are defined https://github.com/livepeer/explorer/blob/main/apollo/subgraph.ts
> 
> You can see how they do the minutes calculation in `usage.tsx` too. It’s based off of fees and a constant pixels per minute that they get from assuming a certain distribution of transcoded frame rates and resolutions. Then they add minutes from livepeer.com usage api which is not public: https://livepeer.com/api/usage

Thanks @ishraq8 I'll keep a note of this, and start working on the subgraph.

**Comment by ishraq8** [comment]
Passed QA, compared to https://explorer.livepeer.org/

the data matches what is on explorer great work @shashwatS22

**Comment by shashwatS22** [comment]
> Passed QA, compared to https://explorer.livepeer.org/
> 
> the data matches what is on explorer great work @shashwatS22

Thanks @ishraq8

**Comment by bye43** [comment]
@dmelotik Just FYI - this has passed QA

**Comment by dmelotik** [comment]
I did my code review yesterday. Working through some final things before merge
