### ISSUE TITLE
Compound Ethereum - Indexing Error

### ISSUE THREAD

**Issue by menaitm** [messari/subgraphs#1737]
**Describe the bug**
Subgraph for CompoundV2 is failing (and has been for several days).

**Reproduction**
https://thegraph.com/hosted-service/subgraph/messari/compound-ethereum

https://okgraph.xyz/?q=messari%2Fcompound-ethereum

**Comment by bye43** [comment]
@menaitm Fix just grafted today, so should be back up - https://thegraph.com/hosted-service/subgraph/messari/compound-v2-ethereum. Thanks!

**Comment by bye43** [comment]
Are you querying the correct deployment - https://okgraph.xyz/?q=QmZWkmLUFVsujVzRjEHj1sKXYVSAqKc853CM9BLQHb3M51 ?

**Comment by menaitm** [comment]
Apparently not - `messari/compound-ethereum` still points to the old deployment: https://okgraph.xyz/?q=messari%2Fcompound-ethereum

This is shown in TheGraph Hosted Service UI too: https://thegraph.com/hosted-service/subgraph/messari/compound-v2-ethereum
![image](https://user-images.githubusercontent.com/106617039/218533826-16f1fc7b-b790-4910-8af1-f9454cbbb43a.png)


Do you know when this updates to the new deployment?

**Comment by menaitm** [comment]
FYI the new subgraph is failing too:
https://okgraph.xyz/?q=messari%2Fcompound-v2-ethereum

Unable to sync blocks since `16,629,297` (Feb-14-2023 08:13:47 PM +UTC)

The logs here are littered with warnings: https://thegraph.com/hosted-service/subgraph/messari/compound-v2-ethereum?selected=logs

**Comment by dmelotik** [comment]
Hi @menaitm thanks for alerting us. This issue was fixed over the weekend. Both the hosted service version/decentralized network version have the latest code. The dec network has to sync from the beginning though..

- [hosted](https://okgraph.xyz/?q=messari%2Fcompound-v2-ethereum)
- [decentralized](https://thegraph.com/explorer/subgraphs/6tGbL7WBx287EZwGUvvcQdL6m67JGMJrma3JSTtt5SV7?view=Overview&chain=mainnet)

The change occured when we began supporting compound V3, and subgraphs cannot be deleted, so it is there. Feel free to reference this subgraph dashboard we use for status/development: https://subgraphs.messari.io/

> You can see the sync/development status's easily from the home page

As far the `warnings` go this is due to positions not being found in the subgraphs. This was a bigger issue a few months ago, but since then we have fixed it and it catches 99% of the "missing" positions. See the issue/fix [here](https://github.com/messari/subgraphs/issues/751)
