### ISSUE TITLE
#bug; rewardTokenEmissions issue on Dex subgraphs

### ISSUE THREAD

**Issue by liambeckman199** [messari/subgraphs#1769]
**Describe the bug**
There are cases when the rewardTokenEmissionsAmount is defined but the rewardTokenEmissionsUSD is 0 on some Dex subgraphs. Is there a specific reason for this or is it a subgraph error?

**Reproduction**
balancer-v2-arbitrum pool
curve-finance-arbitrum
curve-finance-optimism
saddle-finance-arbitrum
sushiswap-fantom
sushiswap-celo
sushiswap-moonriver
sushiswap-gnosis

(potentially more)

**Expected behavior**
For example, on the sushiswap-gnosis subgraph, for the top 10 pools by TVL on the latest daily snapshot, the SushiSwap Wrapped Ether on xDai/Wrapped BTC on xDai pool yields rewardTokenEmissionsAmount= 4974545454545405000 and rewardTokenEmissionsUSD= 0. I would expect to see a non-zero value defined for rewardTokenEmissionsUSD for this snapshot.

**Comment by bye43** [comment]
Hey @liambeckman199! For some of those subgraphs you listed (balancer-v2 arb, curve arb,op), they have not been released as `prod` and are still under development. You can find the list of protocols and the respective status of all their deployments[ here ](https://subgraphs.messari.io/) (click on a protocol to see all the deployments). In terms of rewards for DEXs, we have put those in the backlog for now since they are high-lift atm. Certain protocols do have correct rewards data, but not all. For those sushi deployments, and I suspect most other non-ethereum deployments, the `rewardTokenEmissionsAmount` is correct and the subgraph is pricing the [reward token incorrect ](https://api.thegraph.com/subgraphs/name/messari/sushiswap-gnosis/graphql?query=%7B%0A++liquidityPool+%28id%3A%220xe21f631f47bfb2bc53ed134e83b8cff00e0ec054%22%29+%7B%0A++++name%0A++++id%0A++++rewardTokens+%7B%0A++++++token+%7B%0A++++++++name%0A++++++++id%0A++++++++lastPriceUSD%0A++++++%7D%0A++++%7D%0A++++rewardTokenEmissionsAmount%0A++%7D%0A%7D)resulting in the 0 you see. It is hard to get consistent token pricing and something we are working on, so hopefully we will have a fix out soon.
