### ISSUE TITLE
Portal - Wormhole - MAINNET QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#1779]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=dhruv-chauhan/portal-mainnet-3&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1hh98Q65YXkN_TSYeLqFVLjCY0DF7HrXn/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Total Pool Count and Total Supported Token Count

Portal Bridge website only shows  67 tokens/pools instead of subsgraph data's 897.

### Pool Overview - TVL

- Out of the top 10 pools in the subgraph data, only two pools have shown more than 10% discrepancy with official website TVL data. 
- These two pools/tokens are Tether USD and FTT (FTX Token):

| Subgraph - Tether USD TVL | Portal Bridge Website - Tether USD TVL | Difference % 
| :---- | :--- | :---  | 
| $11,504,614.48| $14,000,000.00 | -17.82%| 

| Subgraph - FTT TVL | Portal Bridge Website - FTT TVL | Difference % 
| :---- | :--- | :---  | 
| $7,057,843.47| $5,000,000.00 | 41.16%| 

- FUTUREGOLDCOIN or FCI token (5th pool) from the subgraph data are not shown in the official website data.

- Refer to the sheet "Pool_Overview" for details

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@dhruv-chauhan QA here looks p minor.

**Comment by bye43** [comment]
@pietydespises Once @dhruv-chauhan addresses these comments can you just give the other deployments besides FTM here a quick look over: https://github.com/messari/subgraphs/pull/1718. Thanks!

**Comment by dhruv-chauhan** [comment]
1) Pool Count
The supported token list on portal's website/api is not exhaustive, confirmed on their discord.
For instance, `Covalent Query Token (CQT)` is not listed on the website but has valid [bridge transactions](https://etherscan.io/tx/0x84a7be1cf00f16f2254813b813ab0133f8debeab0c449ec1645894ecf3f01323) via Portal.
2) Pool TVL
For accurate pool TVL, "it’s probably a better idea to look at the contract custodied amounts", again from their discord.
So, we should assume Token Bridge contract's [token holdings](https://etherscan.io/tokenholdings?a=0x3ee18B2214AFF97000D974cf647E7C347E8fa585) as pool tvl's source of truth.
  - USDT
  matches Token Bridge contract's holding
  - FTT
  inputTokenBalance amount matches Token Bridge contract's holding, discrepancy is due to wrong price reported by our price-lib
  - FCI
  inputTokenBalance amount matches Token Bridge contract's holding, discrepancy is due to wrong price reported by our price-lib. This is some random unlisted token, we could hardcode to ignore it if that seems okay
  
@SerenityFund @bye43

**Comment by pietydespises** [comment]
Agree with the hardcode to ignore FCI for now

**Comment by bye43** [comment]
Reopening per @pietydespises comments above about FTT

**Comment by dhruv-chauhan** [comment]
@pietydespises updates have synced too!
https://subgraphs.messari.io/subgraph?endpoint=dhruv-chauhan/portal-mainnet-3&tab=protocol

**Comment by pietydespises** [comment]
looks good!
