### ISSUE TITLE
#bug; Pools, markets, vaults ids' lack of uniformisation (lowercase, uppercase)

### ISSUE THREAD

**Issue by Octave-byte** [messari/subgraphs#1801]
**Describe the bug**
Pool or vaults addresses are either written with upper and lowercases (lido) or only with lowercases (compound).
Given that graphql is case sensitive when filtering pool IDs, it needs some manual adjustments

**Reproduction**
Where can we see this bug in action?
Lido: https://thegraph.com/explorer/subgraphs/XYcD9VeUvSvuqrsV5pFauXk7jQy9hrnhe5Kb7REyuxm?view=Playground&chain=mainnet with the following request
"{
  pools{
    id
  }
}"

Compound: https://thegraph.com/explorer/subgraphs/6tGbL7WBx287EZwGUvvcQdL6m67JGMJrma3JSTtt5SV7?view=Playground&chain=mainnet with the following request

"{
  markets{
    id
  }
}"

**Expected behavior**
We would expect to have only lowercases pools, vaults or markets ID.

**Comment by dmelotik** [comment]
This is a great point @Octave-byte ! This type of thing comes from old subgraphs, we have since corrected on any new subgraphs. This is something we keep in mind as we develop new subgraphs and schemas now.

Can you help me understand your use case? The ID cannot always be expected to be exactly the contract address of the pool. There are cases where this assumption would break

**Comment by dmelotik** [comment]
Closing, as the fix is encapsulated in #1823 like @bye43 said.
