### ISSUE TITLE
#bug; Euler exploit, multiple pools showing incorrect deposit

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#1869]
**Describe the bug**
Euler was recently exploited through a flashloan+liquidation system: https://twitter.com/peckshield/status/1635203838939652097?s=20
https://twitter.com/FrankResearcher/status/1635241475989721089?s=20

**Reproduction**
In TVL easy to see

1.https://okgraph.xyz/?q=messari%2Feuler-finance-ethereum

**Expected behavior**
TVL and deposits are off.

**Screenshots**
<img width="1145" alt="Screen Shot 2023-03-13 at 10 19 47 AM" src="https://user-images.githubusercontent.com/47088402/224729021-28235cf0-3745-4caf-aa32-39eb40e7149c.png">

**Additional context**
looks like we are following the etokens. This was exploited to pull out the actual assets.

**Comment by tnkrxyz** [comment]
This doesn't look right. Looking into it.

**Comment by tnkrxyz** [comment]
Our number is actually consistent w/ euler's own frontend: https://app.euler.finance , but defillama's number reflects the hack. Will implement defillama's logic post the hack.

**Comment by tnkrxyz** [comment]
Fix in #1880 is ready for review. Will take some time to sync. I verified with a drafted deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/euler-finance-ethereum (protocol.totalValueLockedUSD is negative because I changed the protocol id to lower case and it created a separate protocol entity). The new deployment from scratch should fix this.

**Comment by ishraq8** [comment]
@tnkrxyz Data is fixed and accounts for losses from hack. It can be merged.
