### ISSUE TITLE
Multichain revenue seems to be off

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#1911]
**Describe the bug**

Is the revenue correct? Seems pretty crazy they are making $32M a day

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2354636/226247902-c8f36001-06fe-4b60-b090-5d568f23902e.png">

https://subgraphs.messari.io/subgraph?endpoint=messari/multichain-ethereum&tab=protocol

**Comment by bye43** [comment]
@pietydespises @dhruv-chauhan Can you guys take a look at this?

**Comment by pietydespises** [comment]
@dhruv-chauhan on 3-10 there was a huge spike in volume (cross-referenced with here: https://scan.multichain.org/#/charts/charts-home ) could this be part of the issue?

**Comment by dhruv-chauhan** [comment]
Crazy high revenue figure is wrong and due to wrong pricing of two tokens in particular ([HOGE](https://subgraphs.messari.io/subgraph?endpoint=messari/multichain-ethereum&tab=pool&poolId=0x9b2f9f348425b1ef54c232f87ee7d4d570c1b552), and [GCAKE](https://subgraphs.messari.io/subgraph?endpoint=messari/multichain-ethereum&tab=pool&poolId=0x015cea338ce68bd912b3c704620c6000ee9f4ab9)).

PR #1916 should fix this. (will take some time to sync)
@bye43 @pietydespises
