### ISSUE TITLE
Stargate Finance (Ethereum) Version 1.1.0 - ETH native token bridging not indexed 

### ISSUE THREAD

**Issue by cryptomarabout** [messari/subgraphs#2006]
**Describe the bug**
Currently, transactions involving bridging or swapping the ETH native token to another chain are not counted as "transfer/swap" events in the Messari subgraph for Stargate Finance. This issue is likely caused by the fact that Stargate Finance uses two router contracts: [one for tokens](https://etherscan.io/address/0x8731d54e9d02c286767d56ac03e8037c07e01e98) and [one for ETH](https://etherscan.io/address/0x150f94b44927f078737562f0fcf3c95c01cc2376). Additionally, the methods called are different ("swap" for tokens and "swap ETH" for ETH).

In contrast, a different subgraph (hosted at https://thegraph.com/hosted-service/subgraph/goldennaim/stargate) properly indexes these bridging transactions.

**Reproduction**

- Link to subgraph on [`okgraph.xyz`](https://okgraph.xyz/?q=messari%2Fstargate-ethereum)
- Link on [graph protocol](https://thegraph.com/hosted-service/subgraph/messari/stargate-ethereum)
- Test address having bridged ETH using Stargate Finance: 0x7bE706681520aD7e679D0d0Eeca5DE6E3267Bf29
- Screenshots are present in the section 'Screenshots', the first is the query performed on the valid subgraph, the 2nd one is the expected 'bug' with an empty response (as the subgraph does not contain the transaction).

1. On the Messari subgraph, request the number of transfers in or out of the test address to determine how many bridging transactions occurred.
2. The query on the Messari subgraph will return an empty array because these transactions are not indexed.
3. On the valid subgraph, request the number of swaps of the test address to determine how many bridging transactions occurred.
4. The query on the valid subgraph will return with a swap event as the transaction is properly indexed.

**Expected behavior**
The Messari subgraph for Stargate Finance should properly index native token bridging transactions. The query in the screenshot provided should return data instead of an empty answer.

**Screenshots**
![image](https://user-images.githubusercontent.com/72732919/231781445-01adef44-4d0b-4e70-94b6-662832c1140c.png)
![image](https://user-images.githubusercontent.com/72732919/231781665-8b948135-2ced-46a0-8d1b-35b54497f42d.png)

**Comment by dhruv-chauhan** [comment]
@cryptomarabout thanks for raising this issue!

However, your deduction is not accurate. We do infact track ETH transfers currently.
You can validate this using [query](https://api.thegraph.com/subgraphs/id/QmeVN7eVYN5b42aPnnAv5XpcG7X8zhsNBFB8Q4rY7yHrG1/graphql?query=%7B%0A++bridgeTransfers%28where%3A+%7Bhash%3A%220xd0b6579146c7cf936bb9bef1d267c7595ceb74c3138dad939082775e3f7e3a2d%22%7D%29%7B%0A++%09hash%0A++++transferFrom%0A++++transferTo%0A++++isOutgoing%0A++++token%7Bsymbol%7D%0A++++amountUSD%0A++%7D%0A++ETHtransfers%3A+bridgeTransfers%28where%3A+%7Bpool_%3A+%7Bsymbol%3A+%22S*SGETH%22%7D%7D%29%7B%0A++%09hash%0A++++transferFrom%0A++++transferTo%0A++++isOutgoing%0A++++token%7Bsymbol%7D%0A++++amountUSD%0A++%7D%0A%7D).

But there is a bug, where we wrongly set `transferFrom` field as the router address, instead of the account initiating transfer for bridge-out transactions. This has been rectified in PR #2019  , once merged your [queries](https://api.thegraph.com/subgraphs/id/QmQkzxYG9XUxazHFwHtNVjFa2Wfjqb7wno1eaSLXnUY2fX/graphql?query=%7B%0A++bridgeTransfers%28where%3A+%7Bhash%3A+%220xd0b6579146c7cf936bb9bef1d267c7595ceb74c3138dad939082775e3f7e3a2d%22%7D%29%7B%0A++%09hash%0A++++transferFrom%0A++++transferTo%0A++++isOutgoing%0A++++token%7Bsymbol%7D%0A++++amountUSD%0A++%7D%0A++accounts%28where%3A+%7Bid%3A+%220x7be706681520ad7e679d0d0eeca5de6e3267bf29%22%7D%29%7B%0A++++transferInCount%0A++++transferOutCount%0A++%7D%0A%7D) should work as expected!

**Comment by cryptomarabout** [comment]
I confirm the queries are working on [the API link you sent](https://api.thegraph.com/subgraphs/id/QmQkzxYG9XUxazHFwHtNVjFa2Wfjqb7wno1eaSLXnUY2fX/graphql?query=%7B%0A++bridgeTransfers%28where%3A+%7Bhash%3A+%220xd0b6579146c7cf936bb9bef1d267c7595ceb74c3138dad939082775e3f7e3a2d%22%7D%29%7B%0A++%09hash%0A++++transferFrom%0A++++transferTo%0A++++isOutgoing%0A++++token%7Bsymbol%7D%0A++++amountUSD%0A++%7D%0A++accounts%28where%3A+%7Bid%3A+%220x7be706681520ad7e679d0d0eeca5de6e3267bf29%22%7D%29%7B%0A++++transferInCount%0A++++transferOutCount%0A++%7D%0A%7D), however it does not seem to be deployed on the hosted service.
While the issue is closed, PR merged and subgraph updated 1 month ago, the same query still returns an empty array.

**Comment by dmelotik** [comment]
deployed @bye43 not sure if it needs backfilling

**Comment by bye43** [comment]
No will move to to done
