### ISSUE TITLE
Support for Multichain: ARB, AVAX, BSC, CELO, Gnosis, OP, MATIC

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2021]
```[tasklist]
### Deployment QA Status
- [x] Arbitrum: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-arbitrum
- [x] Avalanche: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-avalanche
- [x] BSC: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-bsc
- [x] Celo: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-celo
- [x] Gnosis: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-gnosis
- [x] Optimism: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-optimism
- [x] Polygon: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-polygon
```

**Comment by dmelotik** [comment]
@bye43 can we get a QA on the new chains?

https://github.com/messari/subgraphs/pull/1705

**Comment by bye43** [comment]
@pietydespises could you give these a quick run through when you get the chance?

**Comment by pietydespises** [comment]
BSC: seems to be missing a lot of metrics (TVL, revenue, volume,...)
Celo: seems to be missing a lot of metrics (TVL, revenue, volume,...)
xDAI: TVL data only goes back a couple months, and missing everything preivous, even though we have data for the other metrics. 
Optimism: Check the extreme spike of TVL on Nov. 13th
Matic: Missing a lot of metrics (TVL, revenue, volume,...)

**Comment by dhruv-chauhan** [comment]
[BSC](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/Qmatei9BqHry74aimbFNRHmsFBcm1QHuqteroG1qTPH9bG&tab=protocol): could've been the pending version when you checked, could you check again on the linked deployment.

[Celo](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRr7Ygm4TzkGynNCzpQma76uAGyEjZXHqEYBvSJN4M4gc&tab=protocol): weird, but looks like everything is infact zero
![Screenshot from 2023-05-05 13-39-33](https://user-images.githubusercontent.com/32761670/237019920-5dca5103-f046-4fc4-b63b-7d36d6e2cf73.png)


[xDAI](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmPqzwqiVn4BCHbw5iXyGsfL5tNiWhsyV84TyW6YeHBmCc&tab=protocol): no prices for tokens from pricefeed (except for `Curve Dao Token on xDai`), hence inaccurate (almost zero) USD fields. Non-USD fields are accurate.
Example, for token `Anyswap`, inputTokenBalance matches official number, token price from pricefeed is 0, TVL USD is 0. 

[Optimism](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmedgxwpsTaeGpeHRwgFSkrLMpx7wvUTim7W1wfThnjrWu&tab=protocol): Looks like there was a [liquidity deposit of ~$13.5mil USDC on Nov-11-2022](https://optimistic.etherscan.io/tx/0x19fe364924d456a6b4c7b3effe7046c0bd98c2d25a0af20370bcc9d3cc17de95) which was later [withdrawn on Nov-14-2022](https://optimistic.etherscan.io/tx/0xdac8794b52524b0e80cf97504e3e1dc2e3609dde8458f97c3877809c4484433c), so the spike in TVL looks legit.
However, the pricefeed only gives prices for USDT, USDC, WETH, WBTC, DAI, and FRAX, zero otherwise. Hence, USD fields for all other pools are zero.

[Matic](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmdxGdGPiwLLFr9hdkN8dNsVhHATPxT3bnVJZXSBeept4M&tab=protocol): Again, could have been the pending version, please check again on the linked deployment.

@pietydespises

**Comment by pietydespises** [comment]
thanks very much @dhruv-chauhan for clearing this up. Matic and BSC look good, and looks like we'll need to hide at least the xDAI deployment.

**Comment by bye43** [comment]
@pietydespises Thoughts on keeping or hiding OP from FE. I would like to have it, but sounds like a large amount of TVL will be missing?

**Comment by pietydespises** [comment]
@bye43 let's keep it, pricefeed might be updated soon

**Comment by pietydespises** [comment]
Hide xDAI and Celo

**Comment by bye43** [comment]
@dhruv-chauhan Will the pricefeed for OP be updated?

**Comment by dhruv-chauhan** [comment]
@bye43 I'm currently not looking into OP pricefeed in particular, changes for the other issues should not affect it.

**Comment by dmelotik** [comment]
What is in master is fully synced on the hosted service @bye43

**Comment by bye43** [comment]
O wait why is it not on subgraphs.xyz? Need to add to deployment.json?
