### ISSUE TITLE
Arbitrum One Bridge - MAINNET

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2041]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmVBAP1mTFbHa5vgQ632LUrKFPkE3AYqf82EtSCPCWz6w2&tab=protocol
| Schema Version  |  1.1.0  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1riP5oo9iIhUoF0gc8wPagzGW5D6a3pD1/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Pool Overview 
- The names of the 1st to 50th pools are illegible/unreadable. 
- Additionally, the addresses of the 2nd to 50th pools cannot be tracked on either DeBank or Etherscan.
- Refer to the sheet 'Pool_Overview'   

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@fortysevenlabs QA for Arbitrum One Mainnet

**Comment by fortysevenlabs** [comment]
> The names of the 1st to 50th pools are illegible/unreadable.

[Pushed a change](https://github.com/messari/subgraphs/pull/1691/commits/359e1d659a73ef31101631b50f17054d4dab5a87) that would make the name legible. The name will be the same as pool id.

**Comment by bye43** [comment]
@fortysevenlabs Instead of the pool name can we use the name of the `inputToken` similar to OP Gateway as seen [here](https://subgraphs.messari.io/subgraph?endpoint=messari/optimism-bridge-v2-ethereum&tab=poolOverview)

**Comment by fortysevenlabs** [comment]
@bye43 assuming you are suggesting we use inputToken name instead of current pool id for pool initialization.

The reason we are passing pool id (gateway and token id concatenated) is because there are some tokens that have matching name and there are some tokens where symbols are empty - this results in non-unique pools and impacts pool metrics calculation as mentioned in a previous comment. We were previously passing concatenation of gateway id and input token symbol.

Arbitrum is also different from Optimism with respect to the contract that emits bridging events. In case of Arbitrum, there are a bunch of gateways that each deal with different tokens so we went ahead with the format of gateway name and input token id concatenation.

We could consider using name / symbol if we ignore a bunch of these tokens but we will need to manage this token list over time.

**Comment by bye43** [comment]
@fortysevenlabs Ahh i think we may be talking about different things. I am just referring to what we are calling the pool name. Right now it, it looks like the name of the pool is the `poolD` and we just want it be readable so the `inputToken` name should suffice. 

![Image](https://user-images.githubusercontent.com/107651107/234082017-7f9644f4-d979-4aa0-9565-01582770f9c1.png)

![Image](https://user-images.githubusercontent.com/107651107/234082036-b85764ea-7106-444e-ba8e-ac1f917d6b25.png)

**Comment by dmelotik** [comment]
Ready to do the final check to ensure all of the issues have been fixed (see the subgraph deployments linked in the PR)

cc @bye43 @pietydespises

**Comment by bye43** [comment]
@fortysevenlabs The Mainnet deployment looks good besides the naming, once that is fixed. The mainnet deployment can be frozen and marked `prod`. I believe the arbitrum deployment needs another look though and I have left some quick comments here: https://github.com/messari/subgraphs/issues/1410

**Comment by bye43** [comment]
Oops, sorry. I see there is a different link in the PR than the one I looked out with the naming fixes, but looks like there is an error with the deployment - https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmepqmDvtKS6AwzY6vvKeMUMGrVRdZWwcCZZ32RhqGjQCf&tab=poolOverview ? Correct me if that is the wrong link
