### ISSUE TITLE
Portal Fantom: TVL spiking

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2087]
@dhruv-chauhan looks like there is a TVL spike for the Portal FTM deployment. I am guessing this is a pricing error. 
![portal-daily-totalValueLockedUSD-050323](https://user-images.githubusercontent.com/107651107/235951427-1636b91b-eb52-435a-a523-f81e6f9ec89b.jpeg)

**Comment by dhruv-chauhan** [comment]
The spike in TVL seems legit. This is due to transfer of 67546451.68 [SFI](https://ftmscan.com/address/0x924828a9fb17d47d0eb64b57271d10706699ff11) worth ~$2.9bil from Fantom to Ethereum.

refs:
- [subgraph event](https://subgraphs.messari.io/subgraph?endpoint=messari/portal-fantom&tab=events&poolId=0x924828a9fb17d47d0eb64b57271d10706699ff11)
- [wormhole explorer](https://wormhole.com/explorer?txId=0xb815183b0910be354d5c2638e6d0e629cc95dd42b6b601a68f92356c43f6cf2e)
- [transaction](https://ftmscan.com/tx/0xb815183b0910be354d5c2638e6d0e629cc95dd42b6b601a68f92356c43f6cf2e)

**Comment by bye43** [comment]
Wow ... ya this looks right. Thanks, I should have took a deeper look. Will close
