### ISSUE TITLE
#investigate; curve swap volume 0 w/ tvl (certain pools)

### ISSUE THREAD

**Issue by dmelotik** [messari/subgraphs#2109]
**Describe the bug**
Some pools have a TVL (so price is being calculated), but there is no `volumeUSD`. 

Right now in the subgraph the `volumeUSD` = `amountInUSD` + `amountOutUSD` / 2

However there are a number of pools that have swap.amountInUSD and swap.amountOutUSD > 0, yet no volumeUSD in the pool. [Example](https://api.thegraph.com/subgraphs/id/QmUiasZYjdq2dPNiAqip67wJo8Px8SAb62sHVMbkqP6cAw/graphql?query=query+MyQuery+%7B%0A++protocols+%7B%0A++++subgraphVersion%0A++%7D%0A++liquidityPool%28id%3A+%220x50b0d9171160d6eb8aa39e090da51e7e078e81c4%22%29+%7B%0A++++id%0A++++totalValueLockedUSD%0A++++cumulativeVolumeUSD%0A++++inputTokens+%7B%0A++++++name%0A++++++lastPriceUSD%0A++++%7D%0A++++inputTokenBalances%0A++%7D%0A++swaps+%28first%3A+3%29+%7B%0A++++amountInUSD%0A++++amountOutUSD%0A++%7D%0A%7D)

Other pools with this behavior:

```
0x50b0d9171160d6eb8aa39e090da51e7e078e81c4
0xc61557c5d177bd7dc889a3b621eec333e168f68a
0xe7e4366f6ed6afd23e88154c00b532bdc0352333
0x6a274de3e2462c7614702474d64d376729831dca
0xcd0148e3f3350f4b98a48535f63a38fc630e80f1
0x92da88e2e6f96cc7c667cd1367bd090adf3c6053
0x7c0316c925e12ebfc55e0f325794b43ead425157
0xc5481720517e1b170cf1d19ceaabe07c37896eb2
```

**Additional context**
Based off my investigation this should not be happening. Is this expected behavior @harsh9200 and do you know why it may be happening?

**Comment by harsh9200** [comment]
@dmelotik the example query you have shared is wrong. All the pools you mentioned have no swaps, which is why the volume is zero. [Query](https://api.thegraph.com/subgraphs/id/QmUiasZYjdq2dPNiAqip67wJo8Px8SAb62sHVMbkqP6cAw/graphql?query=query+MyQuery+%7B%0A++protocols+%7B%0A++++subgraphVersion%0A++%7D%0A++liquidityPool%28id%3A+%220x50b0d9171160d6eb8aa39e090da51e7e078e81c4%22%29+%7B%0A++++id%0A++++totalValueLockedUSD%0A++++cumulativeVolumeUSD%0A++++inputTokens+%7B%0A++++++name%0A++++++lastPriceUSD%0A++++%7D%0A++++inputTokenBalances%0A++++swaps+%28first%3A+3%29+%7B%0A++++%09amountInUSD%0A++++%09amountOutUSD%0A++%09%7D%0A++%7D%0A%7D)

**Comment by dmelotik** [comment]
Thanks @harsh9200 I realized after I posted this 😅

LOL, so yeah this is a non-issue. No swaps = no swap volume
