### ISSUE TITLE
Morpho Aave V2 - MAINNET

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2113]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmVCPdUKWrVvBFQ7wSwLNuVJ65SvfrWYHWAbkhc92D1Zno&tab=protocol
| Schema Version  |  3.0.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1xD8ErqO8_gFnqA7y1Urg8y1tMNCw3N_P/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

###  Revenue

- Based on our calculations using data from the official website, the implied protocol side revenue is not zero. In fact, it should be around $4.3k based on the latest data. 
- There is a significant difference between the daily total revenue and the implied revenue, with a discrepancy of 452.99%. 
- For more detailed information, please refer to the "Support-Revenue" sheet.

As of May 10, 2023

| Subgraph - Supply Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 164,734.54| 25,474.85 | 139,259.69| 546.66%| 

| Subgraph - Protocol Side Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 0.00| 4,315.11 | -4,315.11| -100.00%| 

| Subgraph - Daily Total Revenue | Official Website - Supply Side Revenue | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| 164,734.54| 29,789.96 | 134,944.59| 452.99%| 

- Refer to the sheet 'Protocol'   

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@harsh9200 This is looking good! Just one thing:

- `stETH` pool looks like it has about 10M off in TVL. Not the biggest deal and could be due to pricing, but there is this one spike that looks diff than the morpho UI that is somewhat suspect. 
![Image](https://github.com/messari/subgraphs/assets/107651107/125c5e17-e205-433e-bc8a-0cb781a30529)
![Image](https://github.com/messari/subgraphs/assets/107651107/f8754017-edf0-4f48-9666-f66be26e8528)
