### ISSUE TITLE
Goldfinch Ethereum: Indexing errors 

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2115]
ethereum: 17260147
https://okgraph.xyz/?q=messari%2Fgoldfinch-ethereum
```A determinstic fatal error occured at block 17260147: Mapping aborted at src/mappings/membership/capital_ledger.ts, line 57, column 23, with no message wasm backtrace: 0: 0x67e4 - <unknown>!src/mappings/membership/capital_ledger/handleCapitalErc721Deposit in handler `handleCapitalErc721Deposit` at block #17260147 (2056146d6e4204abc4cde3f0e447cc97c45de5d21f54213b3fb0be77958629f6)```

**Comment by dmelotik** [comment]
Goldfinch added this pool https://app.goldfinch.finance/pools/0x032f7299621c3b68e5d7aceabd567b65e2284da7 in as a non-standard pool. We want to close my PR and simply hardcode this pool in, and make a note in the PR that the subgraph may fail in the future. And we may need to add it in again

**Comment by bye43** [comment]
@ishraq8 whenever you get a chance can you take a look at this?

Deployment and dashboard
- deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/goldfinch-ethereum?selected=logs
- dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/goldfinch-ethereum&tab=protocol

**Comment by dmelotik** [comment]
@ishraq8 with a focus on this pool: `0x032f7299621c3b68e5d7aceabd567b65e2284da7` as it was the one we added in that was causing isssues

**Comment by tnkrxyz** [comment]
> Goldfinch added this pool https://app.goldfinch.finance/pools/0x032f7299621c3b68e5d7aceabd567b65e2284da7 in as a non-standard pool. We want to close my PR and simply hardcode this pool in, and make a note in the PR that the subgraph may fail in the future. And we may need to add it in again

@dmelotik , Goldfinch added a new type of "markets" in addition to the traditional tranched pool, called CallableLoan. The `GoldfinchFactory` contract emits an `CallableLoanCreated(indexed address,indexed address)` event when a CallableLoan market is created. This is causing an indexing error because CallableLoanCreated was not handled, which is fixed in #2195 by adding a handler for CallableLoanCreated and a template for CallableLoan. CallableLoan markets are handled in a way similar to Tranched Pool.

**Comment by ishraq8** [comment]
looks good, QA pass

thanks @tnkrxyz
