### ISSUE TITLE
Mux Protocol - ARBITRUM_ONE

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2170]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmY8zEbstD3gzDyzYSHRMDFR1TLcqiJqnGNXA64dqdg4my&tab=protocol
| Schema Version  |  1.3.1  | 
| Subgraph Version |  1.0.0  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1pHi5JYdOGMACoPSzTpwF6eehiN_heDbL/edit?usp=share_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  Total Pool Count
- The total pool count should be reduced to one instead of three pools.
- On the official website, only the 'MUXLP' pool is displayed.
- Please refer to the 'Protocol' and 'Pool_Overview' sheets for more information.

### Notes on Revenue 
Only sanity check is performed for the revenue, which are within reasonable range but we are not able to further ascertain they are accurate. The official website does not provide specific data for the Arbitrum network, so it's not possible to compute the implied revenue for Arbitrum.

To be specific, the revenue and fee data shows from Defi Llama and Token Terminal are different, likely calculated their revenue data using their own methodologies. The subgraph's revenue is categorized into three components: supply side, protocol side, and stake side. Token Terminal only displays the supply side and protocol side revenue, while Defi Llama only shows the total revenue. 

Please refer to the attached worksheet for more details.

**Comment by bye43** [comment]
@corerouter QA for MUX!

**Comment by bye43** [comment]
@ishraq8 This QA might actually be good on the first go around. If you could quick scan the feedback and give it a final ok whenever you get the chance that would be great!

**Comment by corerouter** [comment]
> @corerouter QA for MUX!

I will study the QA report and give feedback later. Thanks!

**Comment by ishraq8** [comment]
will take a look once courrouter takes a look at initial comments

**Comment by corerouter** [comment]
Thank you very much for the QA report and I highly appreciate it!

On the Total Pool Count, there are two key components in the MUX Protocol: one is MUX Leveraged Trading Protocol, which just likes other Perp protocol and uses MUX own liquidity pool to facilitate trading, while the other is MUX Leveraged Trading Aggregator, which automatically uses other Perp protocol to facilitate trading.  

As there are currently two other protocols, GMX and Gains Trade, which MUX routes user for trading, so right now, there are three pools in the subgraph, MUX own pool, GMX and Gain Trade. The subgraph needs to have pools for GMX and Gain Trade in order to track the trading revenue related with these two protocols which MUX routes users for trading.
