### ISSUE TITLE
#bug; Arbitrum Bridge (Ethereum) Version 1.2.0 - Wrong transaction sender

### ISSUE THREAD

**Issue by cryptomarabout** [messari/subgraphs#2202]
**Describe the bug**
Currently, some transactions involving bridging from Ethereum to Arbitrum are not associated with the correct 'from'/'transferFrom' address. 
I have found an address that used the bridge and the transaction does not appear to be tied to these sender address in the subgraph. I do not know if the problem exists for withdrawals.
By searching using the transaction hash, we can see that the transaction is indexed, but the 'from' or 'transferFrom' entities do not contain the address of the user who did the transaction (addresses contained in the entities seem to be used in the bridging process). As seen on the screenshot, there is no mention of the sender address.

**Reproduction**

Link to subgraph on [okgraph.xyz](https://okgraph.xyz/?q=messari%2Farbitrum-one-bridge-ethereum)
Link on [graph protocol](https://thegraph.com/hosted-service/subgraph/messari/arbitrum-one-bridge-ethereum)
Test address having bridged ETH from Ethereum to Arbitrum: 0xa74cB71969c6476eC42B6fc740D9CE2a496aFD5B
Link to transaction in explorer: [Etherscan](https://etherscan.io/tx/0xbbbafbf100097d1c054b35a9e213c17db42b2b0aa27aaf02e3e09f9312fa3e62)

On the Messari subgraph, request the number of transfers in or out of the test address to determine how many bridging transactions occurred.
The query on the Messari subgraph will return an empty array because these transactions are not indexed.

![image](https://github.com/messari/subgraphs/assets/72732919/f0ffb852-5705-410a-a20d-9289f9ea1c83)

**Expected behavior**
The subgraph should properly index bridging transactions with their appropriate senders.

**Comment by bye43** [comment]
@fortysevenlabs

**Comment by fortysevenlabs** [comment]
Merged the changes to https://github.com/messari/subgraphs/pull/2196 and deployed to [fortysevenlabs/notional-finance-ethereum](https://api.thegraph.com/subgraphs/id/QmeiSDevpumk45sM8RQcwNqWLYz8vvsJ19qECUujoxTDRm)

[Verified the changes on a different subgraph since the above is still syncing:](https://thegraph.com/hosted-service/subgraph/fortysevenlabs/arbitrum-one-bridge-ethereum-m?version=pending)
![image](https://github.com/messari/subgraphs/assets/4187512/90563160-4221-467d-9b75-a76a9bd8b42e)
