### ISSUE TITLE
#bug; Axelar-ethereum revenue is always 0, even though the code seems to track it.

### ISSUE THREAD

**Issue by jaimehgb** [messari/subgraphs#2220]
**Describe the bug**
Axelar only fees are to cover gas costs, as per the README, they are technically not revenue and should be 0. But looking at the code, they are being tracked. The subgraph values show as 0 though.

**Reproduction**
Where can we see this bug in action?

The main axelar-ethereum subgraph.
https://okgraph.xyz/?q=Qmdsc3Um8TJg8Br62oRBNgmr4VtGUxqN9KdxYSBDxkeNt3

**Expected behavior**
Either revenue values are not 0 and README gets updated, or values are left as 0, conflicting code is removed and README clarifies the methodology of axelar revenue.

**Comment by bye43** [comment]
@tnkrxyz any thoughts for above?

**Comment by tnkrxyz** [comment]
Axelar revenue calculation (AxelarGasService) is turned off in #2045. [I decide to keep the handler code](https://github.com/messari/subgraphs/pull/2045#issuecomment-1521108009) because axelar can turn on fees and the handle code will still work. The README has already noted that [revenue is zero](https://github.com/messari/subgraphs/tree/master/subgraphs/axelar#total-revenue-usd)

**Comment by bye43** [comment]
Ahh yes, I remember that now. Thanks for reminding and sounds good

**Comment by jaimehgb** [comment]
Ahhh, I missed this part 👍
