### ISSUE TITLE
Camelot V2 - ARBITRUM_ONE

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#2266]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmZEHXtebo5xBw63nujW3fPSbmUZRThhbTCKDZNzHDRwRe&tab=protocol
| Schema Version  |  1.3.2  | 
| Subgraph Version |  1.0.1  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1a_kCkElNGEc9OBNnH8SSrrYLFZKX-N0D/edit?usp=drive_link&ouid=104027705798814439445&rtpof=true&sd=true |

###  Pool Overview - TVL

- The TVL data for nine out of the top 10 pools closely matches the official website data. However, there is a significant discrepancy of 34.60% in the TVL of the wstETH-WETH pool compared to the official website.

| Subgraph - wstETH-WETH TVL | Official Website - wstETH-WETH TVL | Absolute difference | Difference % 
| :---- | :--- | :---  | :---  | 
| $4,181,986.55| $3,106,946 | $1,075,040.55| 34.60%| 

- Refer to the sheet "Pool_Overview"

Please refer to the attached worksheet for more details.

**Comment by spitko** [comment]
Thanks for the QA.

The wstETH-WETH TVL discrepancy pointed out an important point; there are two different types of pools in Camelot:
https://docs.camelot.exchange/protocol/amm/amm-v2/dual-liquidity-type

Currently prices for all pools were calculated using the standard Uniswap `x * y = k` formula, but this is incorrect for stable pools, for which a different formula must be used.

Changed the code for this in [this commit](https://github.com/messari/subgraphs/pull/2198/commits/bf300837f1724c178cadfe45125de22cb51061bb#diff-fcbf777fe9f8cf0c8252c75217a881f014e1da2f252358e7a9de364aa91c186dR122-R133) and deployed a fix for this [here](https://subgraphs.messari.io/subgraph?endpoint=https%3A//api.thegraph.com/subgraphs/id/QmP6zSvDE5G6xPPcXqeGmwCa2VbSc5Xnbu3L2EhrB57LHe&tab=pool&poolId=0x5201f6482eea49c90fe609ed9d8f69328bac8dda) (from 06-25 onwards). Also redeployed the whole subgraph once more, but that will take a bit longer to complete.

**Comment by bye43** [comment]
@spitko This looks much better! Will take a look at the full synced subgraph once its too head, but should be gtg after that

**Comment by spitko** [comment]
I believe it could be due to the minimum liquidity threshold config set [here](https://github.com/messari/subgraphs/pull/2198/files#diff-d2f54f49e3323d4dad1f092cb83d489578d681f0fc858eea356d36bd236d99b5R216).

For pools with one whitelisted token, if the TVL of the whitelisted token is under the threshold, then the other token's price is set to 0, i.e only the whitelisted token is counted towards the pools TVL.

The reason it was set that high was to reduce TVL pricing issues, but it is possible a lower value would work as well.

**Comment by bye43** [comment]
@spitko ya this is a common problem we have been seeing with DEXs. @dmelotik @steegecs any thoughts here? I assume the best course of action is to just set the threshold lower?

**Comment by steegecs** [comment]
Yeah, I think bringing it down lower is a good idea. 250k is pretty high. How many pricing issues were you running into @spitko ? I am wondering if you could bring this down lower to like 100k or maybe even 50k. Do you think this would make the pricing go crazy? 

I see you also have a very large amount of unlabeled blacklisted tokens and pools, could some of these being missing be part of the issue?

**Comment by spitko** [comment]
The pricing issue happened when the whitelisted token of a pool was drained, then the other token's price never got set to zero. Which meant that pools like [this](https://info.camelot.exchange/pair/v2/0x0926ed87606f8866e7268cbb7496852c4049b3eb), would end up with too high TVLs.

Looking at it again, I think it might be due to the buffer logic built into the findUSDPricePerToken function, which aims to reduce large price jumps. I added an additional check [here](https://github.com/messari/subgraphs/pull/2198/commits/e126feaac6c72fd0e5ab6611541ec611dcd38ea4#diff-fcbf777fe9f8cf0c8252c75217a881f014e1da2f252358e7a9de364aa91c186dR149-R151), which should hopefully resolve this issue. Deployed a new version with this fix and the blacklisted tokens and pools removed, and will keep an eye on it.

**Comment by bye43** [comment]
Sounds good and thanks for the updated @spitko

**Comment by spitko** [comment]
There was one other thing I changed, under `updateInputTokenBalances`, the call to getOrCreateToken updated the token price before the token balances were updated, which meant the new balances used the old price.

https://github.com/messari/subgraphs/pull/2198/commits/aacd13235eb6760b0c38f8d816fcab2a8398bdad#diff-fcbf777fe9f8cf0c8252c75217a881f014e1da2f252358e7a9de364aa91c186d

Here's the full commit, if @steegecs or someone else wants to also look at this. This might be something that should also be changed under the common uniswap-v2 code.

**Comment by steegecs** [comment]
Oh, interesting. Very nice catch @spitko. I like those changes. This is a bit of a pain, but because you are modifying code that impacts all of the uniswap forks, would you mind incrementing the version for all of the uniswap forks subgraphs? Just a patch so 1.0.0 -> 1.0.1.

**Comment by dmelotik** [comment]
@spitko we are still waiting for confirmation on the latest deployed version to check that the TVL issues were fixed.

See latest version: https://okgraph.xyz/?q=messari%2Fcamelot-v2-arbitrum

cc @bye43

**Comment by spitko** [comment]
Latest version also fully synced now:

![image](https://github.com/messari/subgraphs/assets/43212351/8657a08a-33e4-45c2-bad8-a62d32b159b9)

**Comment by bye43** [comment]
This looks good to me! Thanks @spitko
