### ISSUE TITLE
#bug; received null value for amountUSD in convex-finance at block number 17577075

### ISSUE THREAD

**Issue by chenzongxiong** [messari/subgraphs#2275]
**Describe the bug**

**Reproduction**
Where can we see this bug in action?
```
git checkout c9a03c8052ffa6b90758097d571a10d3e59e90fe
messari build convex-finance-ethereum
export thegraph_admin=http://127.0.0.1:8020

# create the subgraph in postgresql
graph create --node $thegraph_admin convex-finance-ethereum
graph deploy --node $thegraph_admin \
--ipfs http://127.0.0.1:5001 convex-finance-ethereum
```

By starting indexing at block number 17577075, such error will occur.

**Expected behavior**
No error occurs, `to` should not be a null value

**Screenshots**
![image](https://github.com/messari/subgraphs/assets/8354165/0986b5cd-5f49-4c9e-b55e-51131e3a6dbd)
<img width="1420" alt="image" src="https://github.com/messari/subgraphs/assets/8354165/2845dc3b-472d-4492-ad44-fc4e76e0dba4">

**Comment by dmelotik** [comment]
Hey @chenzongxiong thank you for this issue! I think what is being described was fixed in this PR: https://github.com/messari/subgraphs/pull/2247

Do you know what `subgraphVersion` you are using in this example? If it is not fixed _still_ please re-open this issue or make another referencing this. THanks!
