### ISSUE TITLE
Beefy Finance Avalanche (Schema Version 1.2.1, Subgraph Version 1.0.2, Methodology Version 1.1.0)

### ISSUE THREAD

**Issue by ishraq8** [messari/subgraphs#561]
<google-sheets-html-origin><style type="text/css"></style>

Subgraph Reviewed | https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/riccardogalbusera/beefy-finance-avax&tab=protocol
-- | --
Date Reviewed | 6-Jul-22
Schema Version | 1.2.1
Subgraph Version | 1.0.2
Methodology Version | 1.1.0

<google-sheets-html-origin><style type="text/css"></style>

Protocol |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Section | Value | Status | Method | Comments |   |   |  
financialsDailySnapshots | totalValueLockedUSD | NOT OK | Public Data | The ending balance matches public info. Historical data does not match public info, e.g. the peak TVL is significantly less. |   |   |  
financialsDailySnapshots | dailySupplySideRevenueUSD | NOT OK | Sanity Check | Negative revenue.  The ratio of protocol-side revenue to supply side revenue is less than the thereotical 4.7% implied by the fee standards of the protocol. |   |   |  
financialsDailySnapshots | cumulativeSupplySideRevenueUSD | NOT OK | Sanity Check | Nagative revenue. |   |   |  
dailyTotalRevenueUSD | dailyTotalRevenueUSD | Not OK | Sanity Check | Negative revenue |   |   |  
financialsDailySnapshots | cumulativeTotalRevenueUSD | Not OK | Sanity Check | Negative revenue |   |   |  
financialsDailySnapshots | protocolControlledValueUSD | NOT OK | Sanity Check | Beefy does not have protocol controlled value. The data in this graph is the TVL. |   |   |  
  |   |   |   |   |   |   |  
Pool Overview |   |   |   |   |   |   |  
TVL |   | NA |   | This page of the subgraph is not displayed. |   |   |  
Rewards |   | NA |   | PoolOverviewTab: Type `Vault` has no field `cumulativeSupplySideRevenueUSD` Type `Vault` has no field `cumulativeProtocolSideRevenueUSD` Type `Vault` has no field `cumulativeTotalRevenueUSD`. Refresh and try again. |   |   |  
  |   |   |   |   |   |   |  
Pool |   |   |   |   |   |   |  
vault schema | Select a pool | Not OK | Public Data | Some pools pools listed no longer on beefy, ie: mim 3crv |   |   |  
vault schema | fees | NOT OK | Public Data | Beefy's fee is 4.5% on earnings made from each vault. Some vaults have a deposit or withdrawal fee. In this case, the withdrawal fee is displayed correctly. |   |   |  
vault schema | totalValueLockedUSD | NOT OK | Public Data | For the MIM pool, contract address had lower amount in beefy site. Mim-curve pool likely depricated by beefy but shows up here |   |   |  
vaultDailySnapshots | totalValueLockedUSD | NOT OK | Public Data | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history.  The data after 16 May 2022 is in line with data from official website. |   |   |  
vaultDailySnapshots | inputtokenbalance | NOT OK | Public Data | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history.  The data after 16 May 2022 is in line with data from official website. |   |   |  
vaultDailySnapshots | outputtokensupply | NOT OK | Public Data | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history.  The data after 16 May 2022 is in line with data from official website. |   |   |  
vaultDailySnapshots | vaultDailySnapshots-outputTokenPriceUSD | NOT OK | Public Data | The outputtokenprice data is close to zero and the table did not display enough decimal place. |   |   |  
vaultDailySnapshots | vaultDailySnapshots-pricePerShare | NOT OK | Sanity Check | The data in the table did not display enough decimal place. Over the 50 days period on the chart, the value of the pricepershare increased from 0.05848 to 0.05855, or 0.12%, annualised 0.9%, different from this pool's APY. |   |   |  
vaultDailySnapshots | vaultDailySnapshots-tokenemissionUSD | NOT OK | Sanity Check | Beefy does not have tokenemission from the pools. should be removed |   |   |  
vaultHourlySnapshots | vaultHourlySnapshots-totalValueLockedUSD | Unsure | Sanity Check | Daily and hourly TVL seems to have similar trend but is off. |   |   |  
  |   |   |   |   |   |   |  
Events |   |   |   |   |   |   |  
Deposit, withdraws |   | NOT OK | Public Data | Withdrawal data has zero in amount and amountUSD. |   |   |  
  |   |   |   | Deposit data seems to be the vault data not the transaction data. |   |   |  
  |   |   |   | Clicking individual entry will lead to Etherscan, rather than Snowtrace |   |   |  
  |   |   |   | Only 3 out the 10 entries in the deposit screen can be matched on Snowtrace. All Snowtrace deposit transactions are matched. In other words, subgraph captured more transactions that's not related to this smart contract. |   |   |  
  |   |   |   | All withdraw entries can be matched on Snowtrace. |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
Additional comments: |   |   |   |   |   |   |  
There is a huge spike transaction on July 9th, hard to do validation since revenue dashboard is not working. Double check when review again. |   |   |   |   |   |   |  
Beefy does not show up on subgraph mainpage have to access manually |   |   |   |   |   |   |

**Comment by RiccardoGalbusera** [comment]
| Section | Value | Comments | Answer |
|-----|-----|-----|-----|
| financialsDailySnapshot | totalValueLockedUSD | The ending balance matches public info. Historical data does not match public info, e.g. the peak TVL is significantly less. | Some of the old vaults don't have events to track harvests and chargedFees, but some vaults also miss events for deposit and withdraws. This issue is not present in more recent vaults |
financialsDailySnapshot | dailySupplySideRevenueUSD | Negative revenue. The ratio of protocol-side revenue to supply side revenue is less than the thereotical 4.7% implied by the fee standards of the protocol. | To account for harvest events that do not return amount harvested, we calculate it as current TVL of the vault minus last stored TVL. This approach can sometimes lead to negative values (for example if in the same block a large withdraw is executed) |
| financialsDailySnapshot | cumulativeSupplySideRevenueUSD | Nagative revenue. | Same as previous entry |
| dailyTotalRevenueUSD | dailyTotalRevenueUSD | Negative revenue | Same as previous entry |
| financialsDailySnapshots | cumulativeTotalRevenueUSD | Negative revenue | Same as previous entry |
| | | | |
| Pool | | | |
| vault schema | Select a pool | Some pools pools listed no longer on beefy, ie: mim 3crv | The vaults are present in the subgraph [https://thegraph.com/hosted-service/subgraph/riccardogalbusera/beefy-finance-avax?query=AVAX%20vault%20query](https://www.google.com/url?q=https://thegraph.com/hosted-service/subgraph/riccardogalbusera/beefy-finance-avax?query%3DAVAX%2520vault%2520query&sa=D&source=editors&ust=1659350604802971&usg=AOvVaw0EMSjF0HvooSCRPsAWIvGY), but TVL is at zero because the oracle fails to fetch the token price |
| vault schema | fees | Beefy's fee is 4.5% on earnings made from each vault. Some vaults have a deposit or withdrawal fee. In this case, the withdrawal fee is displayed correctly. | Can you be more specific about this issue? |
| vault schema | totalValueLockedUSD | For the MIM pool, contract address had lower amount in beefy site. Mim-curve pool likely depricated by beefy but shows up here | The pools indexed by subgraph are all the pools returned by querying beefy api |
| vaultDailySnapshots | totalValueLockedUSD | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history. The data after 16 May 2022 is in line with data from official website. | I think this is a problem on your visualization |
| vaultDailySnapshots | inputtokenbalance | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history. The data after 16 May 2022 is in line with data from official website. | Same as previous entry |
| vaultDailySnapshots | outputtokensupply | The subgraph data is only from May 16 2022, whilst this pool has at least 1 year history. The data after 16 May 2022 is in line with data from official website. | Same as previous entry |
| vaultDailySnapshots | vaultDailySnapshots-outputTokenPriceUSD | The outputtokenprice data is close to zero and the table did not display enough decimal place. | The prices are fetched using the prices scripts provided in the subgraphs repo |
| vaultDailySnapshots | vaultDailySnapshots-pricePerShare | The data in the table did not display enough decimal place. Over the 50 days period on the chart, the value of the pricepershare increased from 0.05848 to 0.05855, or 0.12%, annualised 0.9%, different from this pool's APY. | Same as previous entry |
| vaultDailySnapshots | vaultDailySnapshots-tokenemissionUSD | Beefy does not have tokenemission from the pools. should be removed | |
| vaultHourlySnapshots | vaultHourlySnapshots-totalValueLockedUSD | Daily and hourly TVL seems to have similar trend but is off. | Can you be more specific about this issue? | 
| | | | |
| Events | | | |
| Deposit, withdraws | | Withdrawal data has zero in amount and amountUSD. | Fixed in this PR: https://github.com/messari/subgraphs/pull/525 |
| | | Deposit data seems to be the vault data not the transaction data. | Fixed in this PR: https://github.com/messari/subgraphs/pull/525 |
| | | Clicking individual entry will lead to Etherscan, rather than Snowtrace | I think this is on your side | 
| | | Only 3 out the 10 entries in the deposit screen can be matched on Snowtrace. All Snowtrace deposit transactions are matched. In other words, subgraph captured more transactions that's not related to this smart contract. | Fixed in this PR: https://github.com/messari/subgraphs/pull/525 | 
| | | All withdraw entries can be matched on Snowtrace. | |

**Comment by ishraq8** [comment]
@RiccardoGalbusera Thanks for reviewing this and clarifying the issues. regarding `vaultschema fees` the issue was that beefy front end is showing 4.5% performance fee but our front end was showing 7.77%. I am wondering if this is an issue in the subgraph or on the front end. Or if it is a discrepancy between our calculation vs beefy.

**Comment by dmelotik** [comment]
@ishraq8 I have a better working solution: https://okgraph.xyz/?q=dmelotik%2Fbeefy-finance-avalanche 

it is syncing rn, I did not change anything with prices, so that will likely still be an issue...
