### ISSUE TITLE
AAVE V2 (Mainnet) Schema Version 2.0.1 Subgraph Version 1.2.4 Methodology Version 1.0.0 (maybe other AAVE schemas as well)

### ISSUE THREAD

**Issue by 0xrdt** [messari/subgraphs#699]
This issue seems to happen on other AAVE schemas as well, but I haven't investigated it thoroughly...

Even though It seems like the main problem is with the positions entity, I noticed it when querying the repays entity for a combination of account and market that I'm absolutely sure shouldn't be empty, but is

For example, if you query the repays entity where the market id is 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2 and the account id is 0x5fc9f68333645f713a13f3b3fb9a0f3dedf0f8a7 it will return 0 results:
![image](https://user-images.githubusercontent.com/107650762/182060411-1be8b953-562c-4087-b82a-8708549f684b.png)

I noticed it after the extended schema change that happened on the week of July 25th

**Comment by dmelotik** [comment]
@0xrdt thanks for making this issue.

After a quick investigation I believe the issue lies here: https://github.com/dmelotik/subgraphs/blob/master/subgraphs/aave-v2-forks/src/mapping.ts#L643

If a position is not found during a `Repay`, `Withdraw`, or `Liquidate` the transaction entity never gets saved. This happens frequently from what I see in the logs. This is likely also throwing off the Account balances and positions each time this occurs.

This is also probably an issue in `compound-forks` as well since the same logic is used.

**Comment by dmelotik** [comment]
Relating this issue to #753 #752 #751 as I believe they are all related

**Comment by dmelotik** [comment]
Seems like the specific issue is solved: 
<img width="1034" alt="Screen Shot 2022-10-06 at 10 46 51 PM" src="https://user-images.githubusercontent.com/60583747/194463763-34041439-aada-4672-9363-80169d23290e.png">

If there is anything else hanging, it will get fixed in #1082
