### ISSUE TITLE
Network Ethereum gas prices 

### ISSUE THREAD

**Issue by liambeckman199** [messari/subgraphs#720]
All gas prices on the daily and hourly snapshots are "0" in the Network Ethereum Subgraph.

**Comment by dmelotik** [comment]
@liambeckman199 Thanks for the diligence! I believe you are looking at the old schema, right now the new schema for ethereum is the pending subgraph.

Either way that field is in there, because near returns gasPrice, but evm chains do not.

The new schema makes fields that are not returned in a subgraph bull instead of 0 to reduce ambiguity also.

lmk if you find any other issues in the network subgraph.

**Comment by liambeckman199** [comment]
I see, thanks for the response!

When will the new schema api be available on your Github?

**Comment by dmelotik** [comment]
hey @liambeckman199 I have an outstanding issue with the graph to request more data in the `blockHandlers` (https://github.com/graphprotocol/graph-node/issues/3714) if this data is important to you then it might help to make a note so they know there is more interest in this..

But the new schema is currently syncing (pending) and we are redeploying with a performance improvement since 1.1.0 was very slow for evm chains. You can find links to the subgrpahs here: https://github.com/messari/subgraphs/blob/master/README.md#development-status

**Comment by liambeckman199** [comment]
No immediate rush for the data, but thanks though. Let's stay in touch following the sync.

**Comment by dmelotik** [comment]
This data is unavailable to subraphs given the data we get from blockHandlers. So we are moving this to backlog. It will be something we can add in a network substream though
