### ISSUE TITLE
Banker Joe Avalanche QA

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#866]
https://docs.google.com/spreadsheets/d/1PcbldMq3p35GH5lfuD95SVzoAdaARHXW/edit#gid=129452289

**Comment by dmelotik** [comment]
What to look at:
- ✅ protocol totalBorrowBalanceUSD, off by $10k at one point, think that's okay
- ✅ cumulativeUniqueLiquidatees fixed in previous change
- isActive needs a second look
- canBorrowFrom needs a second look
- look at revenues
- ✅ jWBTC exchangeRate, outputTokenSupply, and outputTokenPrice needs to be looked at
    - says the outputTokenSupply / price are flipped: looks okay to me
    - WBTC may be confusing due to the large price so it looks abnormal compared to other tokens
- ✅ rates flagged for wBTC but i don't see anything wrong

Need to add rewards, even though no rewards have ever been accrued to make future proof.

**Comment by this-username-is-taken** [comment]
@ishraq8 this is ready for another round 🚀

**Comment by ishraq8** [comment]
This looks good. issues are fixed. There was some confusion regarding `outputtokenprice` in the original QA. `outputtoken` will not follow the price of Bitcoin (could be worth zero with no secondary market. `inputtoken` matches perfectly. As always, great work @dmelotik.
