### ISSUE TITLE
Aave v3 OP missing reward token

### ISSUE THREAD

**Issue by this-username-is-taken** [messari/subgraphs#889]
Fix here: https://github.com/messari/subgraphs/pull/886
Being indexed here: https://thegraph.com/hosted-service/subgraph/jaimehgb/aave-v3-graft
Should QA after it fully indexes, then graft

**Comment by jaimehgb** [comment]
The changes alone were QA'd [here](https://github.com/messari/subgraphs/issues/579#issuecomment-1229107363).

It was on a graft from the production subgraph, with the new changes on top. So, wrong past history, but correct present & future. Should it be QA'd again? 

Or can we assume that if rewards are correct today they probably were in the past? Specially since aave-v3 optimism rewards [have been running for less than a month](https://twitter.com/AaveAave/status/1555230478394966018).


```
production-subgraph (wrong rewards)
      |
    block 20400054
       \
        \
         graft-with-changes <---this was QA'd, rewards correct after 20400054
```

**Comment by this-username-is-taken** [comment]
oh you should have your staging deployment index from scratch, and after that fully indexes, you graft it to the production subgraph (i.e. production subgraph will have full history from the staging subgraph, which should be entirely correct)

**Comment by jaimehgb** [comment]
Yes, I have both:
- The one I grafted which has a wrong past -> This one was used to QA the rewards changes so we didn't have to wait to sync from scratch.
- The one that I put to sync from scratch, which will be used to graft into prod.

My question is if the QA done on `1` is enough, or we need to QA `2` before grafting it into prod.

**Comment by this-username-is-taken** [comment]
> Yes, I have both:
> 
> * The one I grafted which has a wrong past -> This one was used to QA the rewards changes so we didn't have to wait to sync from scratch.
> * The one that I put to sync from scratch, which will be used to graft into prod.
> 
> My question is if the QA done on `1` is enough, or we need to QA `2` before grafting it into prod.

Yes we should QA 2. Should be a relatively light QA.

**Comment by jaimehgb** [comment]
Was QA'd and resolved as discussed on this other related issue:
https://github.com/messari/subgraphs/issues/579

**Comment by this-username-is-taken** [comment]
@jaimehgb can we close this?

**Comment by jaimehgb** [comment]
Yes 🙈
