### ISSUE TITLE
dForce Abitrum QA

### ISSUE THREAD

**Issue by SerenityFund** [messari/subgraphs#939]
## Review Info

| Description | Info | 
| :-------- | :--- | 
| Subgraph Reviewed |  https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/dforce-arbitrum&tab=protocol |
| Schema Version  |  2.0.1  | 
| Subgraph Version |  1.1.4  | 
| Methodology Version  |	1.0.0 |
| Evidence Spreadsheet |  https://docs.google.com/spreadsheets/d/1HB1RiUs3lDNReSCpz67PFhNxn4uKGvKr/edit?usp=sharing&ouid=104027705798814439445&rtpof=true&sd=true |

### Interest Rates
The interest rates in the subgraph are substantially higher than the website data. For example, the ETH pool:

|Subgraph Data |Official Website| 
| :---- | :--- | 
| 21.39%, 48.34%  | 1.65%, 3.78% |

### Rewards Rates
The rewards rates for USDT, USDC and DAI in the subgraph are substantially higher than the website data. For example, the USDC pool:

|Subgraph Data USD |Official Website Dr| 
| :---- | :--- | 
| 24.26%, 34.28% | 1.90%, 2.68% |

**Comment by tnkrxyz** [comment]
For interest rate, use the ETH example, the on chain `supplyRatePerBlock` and `borrowRatePerBlock` for the [dforce ETH contract on the ARB chain](https://arbiscan.io/address/0xee338313f022caee84034253174fa562495dcc15#readProxyContract) are  7688516417 and 16319850604, which translates to annual rates of 51.4% and 24.2%, respectively (assuming 1 sec/block, 31536000/year).

For comparison, the numbers on [the ethereum chain](https://etherscan.io/address/0x5ACD75f21659a59fFaB9AEBAf350351a8bfaAbc0#readProxyContract) are 8287067 and 535790899, or annual rates of 0.002% and 0.13%, respectively (assume 13 sec/block, or 2425846/year). They matches the supply and borrow APY on the dforce website: https://app.dforce.network/#/lending?AssetsType=Lend&currentPool=general

**Comment by tnkrxyz** [comment]
The pattern is similar for RewardAPY: the numbers are inline for ethereum chain, but are off for arbitrum. Here it is a bit hard to verify manually than interest rates (in addition, the rewardDistributor contract on the Arbitrum chain hasn't been verified).  But because they uses the exact same code for mapping, it would be strange if the numbers are right for one chain, but the other.

**Comment by Skyge** [comment]
I tend to think dForce use the Ethereum mainnet block number on the Arb, that is 13 sec/block, and 2425846/year.

**Comment by tnkrxyz** [comment]
> I tend to think dForce uses the Ethereum mainnet block number on the Arb, that is 13 sec/block, and 2425846/year.

That is a possibility. I will examine it a bit more. Thanks!

**Comment by tnkrxyz** [comment]
@Skyge , I think you're right - `block.number` ( for example, in [base.sol](https://github.com/dforce-network/LendingContractsV2/blob/55da73310d196849213da2e2357572afdb6d663a/contracts/TokenBase/Base.sol#L108))  returns the block number on ethereum instead of arbitrum block number. 

It can be verified by examining the `UpdateInterest` event. For example, [this transaction](https://arbiscan.io/tx/0x2fddec34088235c5b181344bf4affb2078c69138cf4a08f619f41bd422761488#eventlog) emitted UpdateInterest (at Log Index 0), it is first argument is `currentBlockNumber` and its value is 15612374, which is the [ethereum block number](https://etherscan.io/block/15612374) when the event emitted - the arbitrum block number is [26647293](https://arbiscan.io/block/26647293)

The fix is to change the `ARBITRUM_BLOCKS_PER_YEAR` constant to `ETHEREUM_BLOCKS_PER_YEAR`.
